=pod

=head1 NAME

Dada Mail

=head1 INTRODUCTION

Dada Mail is a contemporary, mature and intuitive web-based
e-mail list management system.

Dada Mail handles Closed-Loop Opt-in subscriptions, sending
complex announce-only and/or discussion mailing list messages with an
advanced, fault-tolerant mass mailing monitor, supports the
archiving/viewing/searching/resending/syndicating (rss, atom feeds) 
of sent messages and doing all this and a whole lot more with style.

Dada Mail can handle custom subscriber fields and searching these fields, allowing you to send mass mailing to only part of your mailing list.  Dada Mail's email templating system allows you to create targeted and
completely custom email messages (mail merging) for each and every one one of your subscribers.

Dada Mail is bundled with additional plugins and extensions to extend
Dada Mail's capabilities. Some of the plugins/extensions support
advanced bounce handling, clickthrough tracking, mass mail scheduling,
blog interfaces of archived messages, AJAX subscription form trickery
and lots of other surprises.

Dada Mail produces HTML5 web content and sticks to best practices
when creating email messages. Write Once: Distribute Everywhere. Dada
Mail is free software that you're able to use, modify, share and enhance
under the terms of the GNU General Public License. Dada Mail is written
in Perl because we love Perl.

Dada Mail's system requirements are minimal: it runs as a CGI script, requires only Perl 5.10.1, supports multiple SQL backend flavors, bundles all of its CPAN Perl module dependencies, and comes with a web-based installer. Download/Upload the distro, run the installer script. 

Dada Mail works well in shared hosting environments thanks to its mass sending throttling capabilities. Dada Mail can also work well with large mailing lists that require a third party email service, like Amazon SES. 

By Justin Simoni

And the Dada Mailers 

=head1 HOMEPAGE

L<http://dadamailproject.com>

=head1 INSTALLING 

L<http://dadamailproject.com/d/install_dada_mail.pod.html>

=head1 DOCUMENTATION

See: 

L<http://dadamailproject.com/d>

Version-specific documentation is located in this distribution, under: 

I<dada/extras/documentation/html_version>

directory. Just open up 'index.html' in a web browser.

=head1 SUPPORT

=over

=item * Discussion Mailing List: 

L<http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dadadev/>

=back 

=head2 See Also: Documentation Links above.

=head1 DEVELOPMENT

Dada Mail is developed openly at: 

L<http://github.com/justingit/dada-mail>
	
"master" - always stable

Mailing List: 

L<http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dadadev/>


=head1 LICENSE AND COPYRIGHT 

Copyright (c) 1999 - 2015 Justin Simoni All rights reserved. 

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
