=pod


=head1 Email Design Resources


=begin html


<p>
	<a href="http://foundation.zurb.com/emails.html">Foundation for Emails</a> - Dada Mail's shipped email templates are 
	created using this Framework. 
</p>

<p><a href="https://mjml.io/">MJML</a> another email markup language to help simplify writing responsive HTML email messages. 
<p>
	<a href="http://briangraves.github.io/ResponsiveEmailPatterns/">Responsive Email Patterns</a><br>
	<em>A collection of patterns and modules for responsive emails.</em>
</p>

<p>
	<a href="http://htmlemailboilerplate.com/">HTML Email Boilerplate.</a>
</p>

<p>
	<a href="http://emailbg.net/">Bulletproof Email Background Images</a>
</p>
<p>
	<a href="http://emailwizardry.nightjar.com.au/">Email Wizardy</a>
	<br />
	<em>Mastering the dark art of HTML email, one UTF-8 encoded character at a time</em>
</p>

=end html

=head2 Books

=begin html

<p>
	<a href="http://www.amazon.com/Create-Stunning-HTML-Email-Works/dp/0980576865">Create Stunning HTML Email That Just Works</a>
</p>
<p>
	<a href="http://www.amazon.com/Email-Marketing-Rules-Straight-Hearts/dp/1484183304">Email Marketing Rules: How to Wear a White Hat, Shoot Straight, and Win Hearts</a>
</p>
<p>
	<a href="http://modernhtmlemail.com/">Modern HTML Email - A guide to building robust, responsive, and effective HTML email.</a>
</p>

=end html

=head2 Testing

=begin html 

<p>
	<a href="http://www.emailonacid.com/">Email on Acid</a>
</p>

=end html

=cut
