=pod

=head2 7.0.5

=head2 Summary 7.0.5

This bugfix release focuses on a few different parts of Dada Mail, to make thingks work soother: 

=over

=item * The Installer was given some TLC, with code being cleaned up, and a few extra options added - look 
for new advanced configuration options for Bridge and Bounce Handler, as well as some of the Debug Trace options. 

=item * The Bounce Handler parsing engine has seen some improvements, to work on some recently submitted bounce messages, that it was 
otherwise not parsing correctly. It's ultimately a work in progress, but we're very happy with how things are continually shaping up

=item * We've work with Bridge, and making sure some of the emails it creates shows message Subjects encoded correctly. There 
was some issues with UTF-8 strings showing either the original encoded, or being double-encoded. 

=item * The, "Backdate" option or archving in the Send a Message (and friends) screen should default to the current date

=back

Also the bugs fixed below: 

=head2 Bugfixes 7.0.5

=head3 Partial list sending settings not saving in Scheduled Mailer

L<https://github.com/justingit/dada-mail/issues/443>

=head3 On Behalf Of (p.p. Mode) can corrupt MIME Words-encoded header phrases.

L<https://github.com/justingit/dada-mail/issues/444>


=head2 7.0.4

=head2 Summary 7.0.4

=head2 Bugfixes 7.0.4

=head3 Backdating archived messages in Send a Message screen does not create a valid date, when archive is saved

L<https://github.com/justingit/dada-mail/issues/441>

=head3 "On behalf of" template placeholder not properly sanitised in bridge config page

L<https://github.com/justingit/dada-mail/issues/440>

=head1 Dada Mail Changelog for v7.x

=head2 7.0.4

=head2 Summary 7.0.4

This is primarily a bugfix release, and in particular, bugs found when using Amazon SES for mail sending. The option, B<Automatically set batching speeds based on your Amazon SES limits>
was causing problems, as the speed it was setting was too high. This is because the SES service does not report back the exact amount of messages sent in a 24 hour period (as it actually should), resulting in Dada Mail making its batch setting speeds using incorrect data. 

We've reverted Dada Mail's auto-batch sending speeds to use the original, more conservative method, and have had great results in our tests of getting this issue to resolve. 

Because of that, anyone that's using Dada Mail v7.0.0 or higher and Amazon SES should most definetly upgrade to this new release. If there are any additional problems, please report them! 

=head2 Bugfixes 7.0.4

=head3 Amazon SES: " Automatically set batching speeds based on your Amazon SES limits " causing mass mailing problems

L<https://github.com/justingit/dada-mail/issues/439>

=head2 7.0.3

=head2 Summary 7.0.3

This is primarily a bugfix release, although some of issues fixed are fairly important things, 
if you are utilizing Profile Fields.

Some work was also done relating to sending with Amazon SES, mostly to provide additional feedback about mail sending, 
as well as retiring unneeded code. Thanks to github user, B<Yunheng> for the code contributions!

Work has also been done with mass mailing, both to provide additional feedback when setting up debugging traces, 
as well as simplifying some of the file locking done during a mass mailing. We hope things will flow smoother for 
people who have had problems with mass mailing in Dada Mail - we're suspecting some stale file locking issues, 
which we've tried to address. 

=head3 Profile Fields cannot be edited in the List Control Panel Under, Membership >> View >> (subscriber's email address)

L<https://github.com/justingit/dada-mail/issues/436>

=head3 Profile Field Information not saved when user Requests a Subscription

L<https://github.com/justingit/dada-mail/issues/437>

=head2 7.0.2

=head2 Summary 7.0.2

This is primarily a bugfix release, although, we've have added a few new Advanced Installation Configuration Options, available to your via The Dada Mail Installer. Here's information on the Advanced Installation Configuration Options available: 

L<http://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html>

Including, 

=over

=item * Enabling/Disabling Global Blacklist

=item * Enabling/Disabling Global Unsubscribe 

=item * Setting the percentage of your total Amazon SES Quota

=back

We've also enabled, B<On Behalf Of (p.p. Mode)> for discussion lists by default, as it seems to be the way to go with things, considering the Yahoo/DMARC Fiasco. B<On Behalf Of (p.p. Mode)> made its debut in v6.8.0 of Dada Mail. 

Finally, we've added some new Bounce Handler rules to handle some of the more usual bounces causes by hitting the DMARC issue. 

=head2 Bugfixes 7.0.2

=head3  Verify screen of Membership » Remove doesn't correctly show email addresses to remove 

L<https://github.com/justingit/dada-mail/issues/434>

=head3 Subscription Requests with Required Profile Fields always cause, "Missing Profile Field" Errors

L<https://github.com/justingit/dada-mail/issues/433>

=head3 

=head2 7.0.1

=head2 Summary 7.0.1

This is primarily a bugfix release - no new features are present in this release, when compared to v7.0.0. The bugs found and resolved are relatively small, and do not include anything related to security or data loss/corruption. Still, we suggest the upgrade to anyone running v7.0.0

=head2 Bugfixes 7.0.1

=head3 Subscribers that have tried to subscribe themselves, and then later are imported in the list control panel, may not show up in the verification stage

L<https://github.com/justingit/dada-mail/issues/431>

=head3 semicolons used to separate paramaters in query strings sometimes causes problems

L<https://github.com/justingit/dada-mail/issues/430>

=head3 Just "Updating" profile fields of addresses without any new Subscribers will not work.

L<https://github.com/justingit/dada-mail/issues/428>

=head3 Default subjects not coming up in Send a Message or Send a URL screens

L<https://github.com/justingit/dada-mail/issues/427>

=head2 7.0.0

=head2 Features

=head3 Private Mailing Lists

Private Mailing Lists allow you to run a mailing list for a closed off group of participants. 

Previous versions of Dada Mail were specifically designed to run B<Public Mailing Lists>: mailing lists where anyone can subscribe to using the mailing list's subscription form, and most I<definitely> everyone can remove themselves (unsubscribe). 

For public mailing lists and marketing purposes, this works just great, but many users want to work with the app for a different purpose: utilizing Dada Mail's mailing list organizational and mass mailing features for a I<private> mailing list of contacts: a group of colleagues, or an internal company mailing list.

Since this wasn't a role that Dada Mail was designed for, it hasn't fared very well, as List Owners became frustrated, having to constantly deal with list members removing themselves (often by accident). The tools to run a private mailing list just weren't there and solutions to this problem felt very hacky.  

Dada Mail now has support for B<Private Mailing Lists>. A private mailing list 
is a mailing list used in a closed, internal setting; not for a mailing list  used publically for marketing purposes. 

When a mailing list's mode is set to, B<Private>, unsubscription links are not required (as they are in a public mailing list), but any unsubscription links found in a mass mailing message will be turned into a link to B<Request Removal>. This request will be sent to the List Owner, who will have the final say on who is removed from the mailing list. 

All other options for a mailing list are still available for a Private List, allowing you to tailor your mailing list to exactly what you need.

More information about Private and Public Mailing Lists:

L<http://dadamailproject.com/d/features-public_and_private_lists.pod>

=head3 Abuse Reporting

Abuse Reporting let's you know if there's problems happening on your mailing list. 

Dada Mail now has the ability to allow users to report abuse on your mailing list. These abuse reports will be emailed to the List Owner, logged, and reported through the Tracker plugin. 

=head3 Subscriber Subscription Date saved as a Timestamp

Subscriber information now includes the Date of Subscription in a the B<Timestamp> column. 

=head3 Default order for Membership >> View Screen, Show/Hide Timestamp Column

New options in the, B<Membership - View> screen in the list control panel allow you to set which column to sort subscribers by default, as well as if the Subscription Date/timestamp column should be shown. 

=head3 Advanced Search/Partial Sending List Options 

The B<View List> screen in Dada Mail's list control panel already has a simple search to find what you're looking for withing your various mailing list members.

This search is simple to use, but sometimes you really need to drill down to specifically what you're looking for. 

This release of Dada Mail includes an B<Advanced Search>, allowing you to search more specifically for exactly what you're looking for. You may now search by email address, any profile field independently, as well as between subscription date ranges. 

Partial sending works the same way and the ability to send to members who have been subscribed between a range of two dates is also available. 

=head3 Mass Update of Profile Fields, based on Advanced Search


Once you've done an advanced search on your subscribers, you now have the ability to update any of the Profile Fields of your search results, en mass.

=head3 Support for Required Profile Fields

Profile Fields can now be marked as, B<Required>. Form field validation is done on the subscription form,  both client and server side. The JSON web service API also supports required Profile Fields. 

=head3 More Powerful List Control Panel Address Importing, Mass Updating

The List Control Panel Add/Subscribe/Invite screen now comes with a ton of new, and useful options and utilities:

=head4 Preserve or Update Profile Field Data

In previous versions of Dada Mail, any Profile Field data you try to import could potentially be discarded, if the address you're importing already has profile field data saved. This is because profile field data is shared between mailing lists, and importing a subscriber into a mailing list, may inadvertantly wipe out already saved information you wanted to keep.

Dada Mail now has the option to either preserve any already-existing profile field data, or update this data that already exists. This choice on what to do can be made during the Verification step. 

=head4 Profile Field Data Validation

Since Profile fields can now be required, Dada Mail also checks for any required Profile Fields and will present you with the addresses that are missing these Profile Fields, in the verification step. An option also exists subscribe addresses that are missing the required Profile Fields.

Dada Mail now has the option to allow you to mass update the Profile Fields data of subscribers who are already subscribed, stopping you from needing to fully remove subscribers, just to reimport them. 

=head4 Profiles and Profile Passwords

Along with Profile Fields, Dada Mail can now allow you to set a Profile Password when importing subscribers. This Profile Password allows your user to log into their own Profile, and make changes to their mailing list subscriptions. Profiles are only made if a Profile Password is created.

=head2 Changes 7.0.0

See the entire v6.x to v7.x doc: 

L<http://dadamailproject.com/d/dada6_to_dada7.pod.html>

=cut
