=pod

=encoding utf-8

=head1 Dada Mail Changelog for v8.x

=head2 8.2.0

=head2 Features

=head3 Recurring Scheduled Mass Mailings

Recurring Scheduled Mass Mailings have been integrated into the core of Dada Mail, having only been available before in the now retired Beatitude plugin. 

Set a beginning and end date of your mass mailings, the time they should all go out, and the days of the week that you would like the mailings to be sent. 

More information on Single and Recurring Scheduled Mass Mailings can be found here: 

L<http://dadamailproject.com/d/features-scheduled_mass_mailings.pod.html>

=head2 Bugfixes 

=head3 Unsubscription Requests Do Not Work in the List Control Panel

L<https://github.com/justingit/dada-mail/issues/508>

=head3 CC addresses not removed from bridge email when using SES

L<https://github.com/justingit/dada-mail/issues/507>

=head2 8.1.0

=head2 Summary

This release primarily introduces Magic User Templates as an experimental feature. 

=head2 Features

=head3 Magic User Templates (Experimental) 

Magic Templates allow you to simply set a URL to fetch a webpage, which will then be utilized as your global user template. Various options to adjust the output of your template are available, all of which are available in the included Dada Mail Installer's Advanced Configuration: 

L<http://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html#Configure-Global-Template-Options>

=head2 8.0.3

=head2 Summary

This is a bugfix release of Dada Mail.

=head2 Bugfixes

=head3 Problems creating new list if errors present in values passed 

L<https://github.com/justingit/dada-mail/issues/506>

=head3 Subscription Form: Restful Subscribe API not working in jsonp mode 

L<https://github.com/justingit/dada-mail/issues/505>

=head3  Membership >> Remove Subscribers throws, "Yikes!" error when you attempt to upload a file

L<https://github.com/justingit/dada-mail/issues/504>

=head3  Tracker plugin: Bounce Handler reports do not show in modal window 

L<https://github.com/justingit/dada-mail/issues/503>

=head3 Images don't show in archive view in Chrome

L<https://github.com/justingit/dada-mail/issues/502>

=head3 Gravatar Images break with p.p. mode enabled
 
L<https://github.com/justingit/dada-mail/issues/500>

=head3  Minimal Subscription Form does not have correct form field name 

L<https://github.com/justingit/dada-mail/issues/499>

=head3 Version Check Broken

L<https://github.com/justingit/dada-mail/issues/498>

=head3  Rejected Emails not being attached

L<https://github.com/justingit/dada-mail/issues/496>

=head3  Extra Bracket in multiple_subscribe.cgi 

L<https://github.com/justingit/dada-mail/issues/495>

=head2 8.0.2

=head2 Summary

This is a bugfix release of Dada Mail.

=head2 Bugfixes

=head3 Amazon SES 

Recently, Amazon SES seems to have slightly changed the way it has been returning results to its API calls, 
specifically when finding your daily email sending quotas. This change has caused problems with Dada Mail's 
method of setting its auto-batching capabilities. (fixed) 

L<https://github.com/justingit/dada-mail/issues/491>

=head3 Installer

Advanced Options to set the Confirmation Token expiration date were not being written to the global configuration. (fixed) 

L<https://github.com/justingit/dada-mail/issues/492>

=head2 8.0.1

=head2 Summary

This is a bugfix release of Dada Mail, but touches upon a multitude of problems uncovered after the release of v8.0.0 of Dada Mail.

=head2 Enhancements 

=head3 Admin Menu: Tracker, Mass Mailing Options

Both the Tracker and Mass Mailing Options link in the admin menu will show additional information that reflects data and settings of your mailing list

Tracker will show the number of mass mailing campaigns that have been analyzed in the Tracker plugin. 

Mass Mailing Options will show your current batch sending speeds in messages per hour. 

=head2 Bugfixes

=head3 Bridge

Several problems with encoding have been found in Bridge, most notably when a message in 8bit Content Transfer Encoding and UTF-8 Encoding is sent. Messages are, by default, handled in a different Content Transfer Encoding (quoted-printable), which is basically 7bit. Problem happens if you try to work with these two Content Transfer Encodings together - basically corruption of text. 

To counteract this, messages received by Bridge are first changed to whatever the internal Content Transfer Encoding is, then processed as usual. 

=head3 Archives w/Inline File Attachments

Somewhat related to Bridge, archives with inline file attachments wouldn't  show up correctly. (fixed)

L<https://github.com/justingit/dada-mail/issues/482>

=head3 Multiple Subscribe Extension Script

Subscription confirmation in the C<multiple_subscribe.cgi> extension script would fail, if you have a Profile Field that is required, even if it's submitted with the form. (fixed)

L<https://github.com/justingit/dada-mail/issues/481>

=head3 Profiles

Profiles had several issues: 

=over

=item * Logging in, after subscription

After a subscription is made, the subscriber should be logged into their profile right afterwards (via a session cookie) and able to visit their profile via the really big button presented to them, without having to know their current login information. This was broken (fixed). 

Also, when this was broken, it wasn't clear why things didn't work, as no useful error message was presented (fixed). 

=item * HTML formatting

Several errors in the HTML was present in the Profile Home screen, leading to some of the interface to be broken. (fixed)

L<https://github.com/justingit/dada-mail/issues/479>

=item * Logging In

There seemed also to be a problem with merely logging into you Profile in some instances. (fixed)

=item * Registering an already-existing account

It was also called to our attention that you could still attempt to register an already existing account, even though there's a check in place to hault such an action. (fixed)

=back

=head3 Send a Webpage

Many problems have cropped up in the Send a Webpage screen, some having to do with problems with encoding (again), and others, when specific types of data are included in the webapge, including linked stylesheets. This would ultimately cause a sending to fail. (fixed)

Send a Webpage also suffered from a problem with using the option to set a custom PlainText alternative - seems as if that option was never correctly utlized, and the auto-generated version would always be used (fixed)

L<https://github.com/justingit/dada-mail/issues/485>

=head3 List Invitations

Like most administration list control panel screens in Dada Mail, the List Invitation screen can be disabled, if you are logged in with the List Password. That's done in the list control panel screen, I<Your List Control Panel - Customize Feature Set>

List Invitation doesn't have its screen available in the menu, so it's a little bit of a quess on how to fully disable this. The way it should work is by disabling, I<Membership - Invite/Subscribe/Add>, but this does not work - rather disabling I<Mail Sending - Mass Mailing Options> did this trick, which is nonsensical. (fixed)

L<https://github.com/justingit/dada-mail/issues/486>

=head3 Subscription Confirmation URL Redirect

The URL redirect after a subscription confirmation led to a blank page (fixed) 

L<https://github.com/justingit/dada-mail/issues/488>

=head3 Installer: Setting .dada_files location

It seems that there was a bug related to setting a custom location for the C<.dada_files> directory location. Your custom choice would 
not be tried out, although the installer would come back and tell you that what you've chosen won't work - maddening. (fixed) 

L<https://github.com/justingit/dada-mail/issues/480>

=head3 Log Viewer 

Looks like the Log Viewer plugin always thinks you're logged in w/the List Password, even if you're logged in w/the Root Pass. There's some other oddities I'll also address. (fixed)

L<https://github.com/justingit/dada-mail/issues/489>

=head3 Problems logging out, changing List Password

Changing the List Password works, but you will refresh to a server error screen. Seems there's some problem with the logout() method that seems to be touched quite a few times in the code. (fixed)

L<https://github.com/justingit/dada-mail/issues/490>

=cut
