=pod

=encoding utf-8

=head1 11.1.1

=head2 Bugfixes

=head3 Multiple Subscribe option inside Plugins menu throws syntax error.

L<https://github.com/justingit/dada-mail/issues/750>

=head3 Custom "from_phrase" and "subject" set in email theme templates not used with Full Layout 

L<https://github.com/justingit/dada-mail/issues/749>

=head1 11.1.0

=head2 Features

=head3 Markdown Support

Many pieces of plain text copy in Dada Mail are now treated as Markdown markup, and will be treated as such if/when the copy
is used as HTML. 

List Settings that will get this treatment include: 

=over

=item * Mailing List Description

=item * Mailing List Physical Address

=item * Mailing List Privacy Policy

=back

Along with these list settings, mass mailing messages that are authored in plaintext will be treated as Markdown markup if they 
are converted to HTML. 

=head1 11.0.5

=head2 Bugfixes

=head3  Mass Mailing Broken - errors about missing, "To" header #744 

L<https://github.com/justingit/dada-mail/issues/744>

This bug, unfortunately, will affect ALL users of at least version 11.0.5 of Dada Mail. If you are using that version, it's 
recommended to upgrade. 

=head3  Bridge: Mass Mailings do not work: "Argument contains empty host portion of address at" error #745 

L<https://github.com/justingit/dada-mail/issues/745>

Similar story on this bug. 

=head1 11.0.4

=head2 Bugfixes

=head3 Upgrading via CLI does not set up WYSIWYG editors/file manager correctly #743

L<https://github.com/justingit/dada-mail/issues/743>

=head1 11.0.3

=head2 Bugfixes

=head3 List Invitations do not work #740

L<https://github.com/justingit/dada-mail/issues/740>

This most likely affect v11.0.2 users, as changes in that ver. touched on the code where this bug was introduced. 

=head3  Resending subscription confirmation requests will fail if there are list consents #741 

L<https://github.com/justingit/dada-mail/issues/741>

=head1 11.0.2

=head2 Bugfixes

=head3 Custom Preheader is not set for Subscription Confirmation Message (and probably others) #736

L<https://github.com/justingit/dada-mail/issues/736>

=head3 UTF-8 characters in email headers of email templates cause server errors #735

L<https://github.com/justingit/dada-mail/issues/735>

=head3 Custom "to_phrase" and, "from_phrase" set in email theme templates aren't always actively used in email messages sent out #734

L<https://github.com/justingit/dada-mail/issues/734>

=head3 "Recent Activity" screen still uses dada.txt log file, rather than, "dada_consent_activity" table #733

L<https://github.com/justingit/dada-mail/issues/733>

=head3 Custom To/From phrases as well as Custom Subject do not get applied correctly #721

<https://github.com/justingit/dada-mail/issues/721>

=head1 11.0.1

=head2 Bugfixes

=head3 Digests not working in v11.0.0 #732

L<https://github.com/justingit/dada-mail/issues/732>

=head3  "Website URL" and, "Backlink URL" use same list setting key name #731 

L<https://github.com/justingit/dada-mail/issues/731>

Unfortunately, I had to choose one setting to work with one feature, and make the other setting use a different key. 

I've chosen to have the "backlink" URL and Nmae to use different keys. 

=head3  Imported Addresses w/Profile Fields show incorrectly decoded UTF-8 characters #730 

L<https://github.com/justingit/dada-mail/issues/730>

=head3 "Form Fields" listing lacks List Consents #727 

L<https://github.com/justingit/dada-mail/issues/727>

=head3 "Minimal Subscription Form" HTML code lacks List Consents #726 

L<https://github.com/justingit/dada-mail/issues/726>


=head1 11.0.0

=head2 Major Changes: GDPR Compliance

This version has been released almost exclusively to help users/administrators of Dada Mail to more 
easily comply with the GDPR. 
More information about what has changed can be found in the included L<GDRP Guide for Dada Mail|http://dadamailproject.com/d/gdpr_guide.pod.html>

=cut