=head1 6.1.0

=head2 Summary 6.1.0

This release of Dada Mail features a new URL confirmation system that is hoped to be more secure 
and less easy to spoof than previous iterations of Dada Mail. Since the previous system has been used 
in one form, or anothr, in Dada Mail since the original release of the app in 1999, we highly suggest literally I<anyone>
running Dada Mail to upgrade.

An extended reasoning and explaination for the changes made in this version can be found at: 

L<http://dadamailproject.com/cgi-bin/dada/mail.cgi/archive/homepage_blog/20130218232934/>

As always, we look forward to your feedback about the changes and enhancements we make in Dada Mail. 

=head2 Bugfixes 6.1.0- 

=head3  Profile Unsubscribe links for plus-addresses don't work 

https://github.com/justingit/dada-mail/issues/351

=head3 PlainText to HTML Mass Mailing Messages break ending tmpl_if, tmpl_unless, tmpl_loop blocks

https://github.com/justingit/dada-mail/issues/350

=head3 Bridge stops list processing if one list has a problem

https://github.com/justingit/dada-mail/issues/348

=head3 No entity found! die'ing! at bridge.cgi line 467

https://github.com/justingit/dada-mail/issues/346

=head2 Summary 6.0.2

This release fixes bugs found in the v6.0.1 version of Dada Mail. It's a suggested upgrade for anyone
running v6.0.0 or v6.0.1

=head2 Bugfixes 6.0.2

=head3  <!-- tmpl_strftime [...] --> template tags don't work 

https://github.com/justingit/dada-mail/issues/345

=head3  Bridge: "Setup as" Email Forward/POP3 Account option used when cloning a list 

https://github.com/justingit/dada-mail/issues/344

=head3 "Not Allowed to Post" Message, grammatical error 

https://github.com/justingit/dada-mail/issues/343

=head3 Bridge: Transactional email messages, specific to Bridge/Moderation do not have correct encoding 

https://github.com/justingit/dada-mail/issues/342

=head3  Messages converted from PlainText to HTML will have broken template tags 

https://github.com/justingit/dada-mail/issues/341

=head3 Transactional Emails are bring coverted from PlainText to HTML 

https://github.com/justingit/dada-mail/issues/340

=head3  Domain Stats broken for PlainText Backend 

https://github.com/justingit/dada-mail/issues/339

=head3  Scheduled Mailings HTML window missing v6 

https://github.com/justingit/dada-mail/issues/338

=head3  jQuery UI images with wrong paths in jQuery stylesheet 

https://github.com/justingit/dada-mail/issues/337

=head3 "Your List Control Panel » Customize Feature Set" Broken 

https://github.com/justingit/dada-mail/issues/336

=head3 Removing Stale POP3 Locks doesn't work 

https://github.com/justingit/dada-mail/issues/335

=head3  Multiple Subscribe doesn't seem to be working 

https://github.com/justingit/dada-mail/issues/334

=head3 Error when creating a new profile account. 

https://github.com/justingit/dada-mail/issues/333


=head1 6.0.1

=head2 Summary 6.0.1

This release features one minor bug fix to the Bridge plugin, no other code changes are present. If you are using the v6.0.0 B<Stable> release, 
but are not using the Bridge plugin, this upgrade is entirely optional. 

If you're already running v6.0.0 Stable of Dada Mail, and would like to simply replace the I<dada/plugins/bridge.cgi> 
script, with the fixed version, you may do so: 

L<https://github.com/justingit/dada-mail/blob/8547605c588d6ed5ee59d08698863e6986b8d3f4/dada/plugins/bridge.cgi>

=head2 Bugfixes 6.0.1

=head3 Bridge: Label not found for 'next QUEUE' at bridge.cgi line 1196

L<https://github.com/justingit/dada-mail/issues/332>

=head1 6.0.0

=head2 Summary 6.0.0

This major release of Dada Mail includes major changes to the Dada Mail codebase. A detailed explanation of these changes, compared to v5 of Dada Mail can be found at, 

L<http://dadamailproject.com/d/dada5_to_dada6.pod.html>

When upgrading from I<any> previous version of Dada Mail, make sure to create a new C<.dada_config> file, as old C<.dada_config> files will not work with v6 of Dada Mail. 

=head1 6.0.0 Release Candiate 2

=head2 Summary 6.0.0 Release Candidate 2

The changes below summarize the differences between RC1 and RC2 of the v6.0.0 Release

=over

=item * Membership >> Invite/Subscribe/Add was not functional, for anything except for the Subscribers sublist

This was a problem of a missing class in the, B<Add Checked Addresses to [sublist]> button. 

=item * Mass Mailing Started/Finished log messages were truncated

These log messages were missing some of the information that should have been present. 

=item * "Mass Mailing Finished" Message had the incorrect "finishing time" and, "Duration Time"

=item * Plugin URLs and Installer URL better guessed

The installer and plugin URLs attempt to guess their own URL, so you do not need to configure these things, yourself. 

Unfortunetly, it does not always get them right, depending on your hosting environment. Code has been added to make this guess better. 

=item * Screen Cache plugin's HTML has now been templated out

=item * Beatitude: Some options could not be saved, due to sloppy HTML

=item * CKEditor and the, "{C}" string: 

CKeditor seems to place the, "{C}" string in the source of HTML messages, when there'a a comment tag in an, "href" tag attribute (like, for example, in a link). Since Dada Mail's template tags are also valid HTML comments, they are found in, "href" attributes often. 

This string is never I<removed> by CKeditor, and thus, will break the link. It seems that this character is some sort of placeholder for comment tags, but seems not to be handled correctly by CKeditor. 

This string is now looked for, and removed, before messages are sent. 

=item * "Automatically set batching speeds based on your Amazon SES limits" was not functioning correctly 

=item * The Default CAPTCHA type was not working correctly, always returning an error

=item * Better support for server environments that don't support data sent via Path Infos

There's a trick in Dada Mail, where you can set the Program's URL to have a, "?" at the end of the URL, like this: 

	$PROGRAM_URL = 'http://example.com/cgi-bin/dada/mail.cgi?'; 

Which will then turn any Path Info, into a query string

Dada Mail will now correctly look for this, and use any information that I<looks> like a Path Info, passed as a query string as Path Info information and also correctly read double-question mark query strings correctly as well. 

It's still a hack-y workaround, but hopefully, could help someone get their work done. Is this a problem with "Zeus" webservers?

=item * Installer: now correctly removes the old screen cache, during an install/upgrade

=item * Installer: now correctly set the, $PROGRAM_ERROR_LOG variable, even if the .dada_files location is set to, "auto"

=item * Bounce Handler: web-based interface to parse bounces broken

The web-based interface to check any awaiting messages and parse them would look as if you're testing messages, but the messages would actually be parsed, scored and logged, except the messages would not be removed. This has been fixed. 

=back