=pod

=encoding utf-8

=head1 11.0.2

=head2 Bugfixes

=head3 Custom Preheader is not set for Subscription Confirmation Message (and probably others) #736

L<https://github.com/justingit/dada-mail/issues/736>

=head3 UTF-8 characters in email headers of email templates cause server errors #735

L<https://github.com/justingit/dada-mail/issues/735>

=head3 Custom "to_phrase" and, "from_phrase" set in email theme templates aren't always actively used in email messages sent out #734

L<https://github.com/justingit/dada-mail/issues/734>

=head3 "Recent Activity" screen still uses dada.txt log file, rather than, "dada_consent_activity" table #733

L<https://github.com/justingit/dada-mail/issues/733>

=head1 11.0.1

=head2 Bugfixes

=head3 Digests not working in v11.0.0 #732

L<https://github.com/justingit/dada-mail/issues/732>

=head3  "Website URL" and, "Backlink URL" use same list setting key name #731 

L<https://github.com/justingit/dada-mail/issues/731>

Unfortunately, I had to choose one setting to work with one feature, and make the other setting use a different key. 

I've chosen to have the "backlink" URL and Nmae to use different keys. 

=head3  Imported Addresses w/Profile Fields show incorrectly decoded UTF-8 characters #730 

L<https://github.com/justingit/dada-mail/issues/730>

=head3 "Form Fields" listing lacks List Consents #727 

L<https://github.com/justingit/dada-mail/issues/727>

=head3 "Minimal Subscription Form" HTML code lacks List Consents #726 

L<https://github.com/justingit/dada-mail/issues/726>


=head1 11.0.0

=head2 Major Changes: GDPR Compliance

This version has been released almost exclusively to help users/administrators of Dada Mail to more 
easily comply with the GDPR. 
More information about what has changed can be found in the included L<GDRP Guide for Dada Mail|http://dadamailproject.com/d/gdpr_guide.pod.html>

=cut