=pod

=encoding utf-8

=head1 Dada Mail Changelog for v9.x

=head1 9.1.2

This is mostly a bug-fix release, fixing bugs found in the v9.1.1 release.

=head2 Bugfixes

=head3 Incorrect .htaccess in the dada/extensions directory 

There was an errant .htaccess file in the dada/extensions directory, disallowing access to any of the directory contents, including extensions you may have been running. This has been removed!

=head3 Mailhide encode sometimes fails with strange input 

L<https://github.com/justingit/dada-mail/issues/548> 

=head3 Sending / Options - "Save For Selected Mailing Lists" button is editable not clickable

L<https://github.com/justingit/dada-mail/issues/547>

=head3 https://github.com/justingit/dada-mail/issues/546

This is a very strange, and quite large bug. It basically affects anything where you need an email sent for Profile work: registering, retrieving a new password, etc, 

L<https://github.com/justingit/dada-mail/issues/546>

=head3 Dada 3 -> 4 utility script was broken

Looks like the following script was not working for v9 of Dada Mail: 

Lhttp://dadamailproject.com/d/dada3_to_dada4_sql.pl.html>

This script is still useful, if you're upgrading from v3 of Dada Mail, are using the SQL backend, and also have profile fields. We've updated it to work correctly with v9. 

=head3 Subscription forms in Dada Mail using JSONP, rather than JSON

Dada Mail's subscrption forms that you see on the default screen, as well as the list screen's now use JSONP in the background to do their work. This is to workaround Same Origin Policies, that even effect calls from diffrent subdomains of the same domain (ie: example.com and www.example.com)

=head2 Changes

=head3 Disabling IP Check in List Control Panel sessions

By default, Dada Mail will look at the IP address that a user is said to be logged in from, and compare it to the IP address in the session data. If they do not match, the session will fail, and you will be booted out of the session. 

Sometimes, this does not work as expected, so we've now allowed you to disable this feature: 

In the Installer under, B<Advanced Configuration>, check, B<Configure Security Options>. Then, I<uncheck> the option, B<Check for Matching IP Addresses>. Done! 


=head1 9.1.1

This is mostly a bug-fix release, fixing bugs found in the v9.1.0 release - of note, we broke the Tracker plugin, with the v9.1.0 release. We've also added some additional .htaccess files in directories of Dada Mail that you may not want snooping in. 

=head2 Bugfixes

=head3 Tracker plugin does not run

https://github.com/justingit/dada-mail/issues/543

=head1 9.1.0

=head2 Features

=head3 Save to Multiple Lists at Once

B<Previously:> One frustration of working with a large collection of different mailing lists with Dada Mail 
is that each mailing list must be administrated one at a time, so it was not possible to make
changes to mailing list settings fo all mailing lists at once. 

B<Now:> with v9.1.0, we've introduced the ability to saving List Settings to multiple mailing lists at once. 

The following list control panel screens support this feature: 

=over

=item * Mass Mailing - Options

=item * Membership - Options

=item * Sending - Options

=item * Sending - Mass Mailing Options

=item * Archives - Options

=item * Archives - Advanced Options

=item * Appearance - Email Message Template 

=item * Appearance - HTML Screen Template 

=item * Plugins/Extensions - Tracker

=back

To use this feature, log into a mailing list with your B<Dada Root Password>, otherwise the feature will not be available. Look for the button labeled, B<Save For Multiple Lists...>. When clicked, a modal window will open allowing you to select the mailing lists that you would like to save the list settings for that list control panel to. 

By default, all the available mailing lists are selected, but you may customize this if you would like. 

=head2 Bugfixes

=head3  Login Switch links sometimes hit server security filters 

L<https://github.com/justingit/dada-mail/issues/542>

=head3 

=head1 9.0.3

This is mostly a bug-fix release, fixing bugs found in the v9.0.2 release 

=head2 Changes

We've made some changes in the B<Membership - View> screen to make loading a bit more apparrent, stopping the user from guessing if things are working correctly. We're utilizing a JavaScript library called, spin.js (L<http://spin.js.org/>) to help out on making the loading screen. Thanks, min.js! 

We've also made similar changes to the Tracker plugin's default screen, as well as preloading some of the easier-to-create data before the rest of the data is availabl. 
Crunching the numbers to show the table of analytics may take a while, if you have busy lists! Now, you'll have access to the individual message reports before the index report is ready. 

=head2 Bugfixes

=head3  Filter Subscribers Through the Black List Broken 

L<https://github.com/justingit/dada-mail/issues/536>

=head3 Core5 Filemanager returns URL, relative to site root, which is broken when email w/image is sent 

L<https://github.com/justingit/dada-mail/issues/533>

=head3 Alert boxes showing errors hard to distinguish 

L<https://github.com/justingit/dada-mail/issues/532>

=head1 9.0.2

=head2 Summary 

This is mostly a bug-fix release, fixing bugs found in the v9.0.0 + v9.0.1 release 

=head2 Changes

=head3 Amazon SES Automatic Batch Settings

Dada Mail can set up your Batch Settings for your mailing list automaticaly, using your daily quota, and per-second limits set by Amazon SES. It does so fairly conservatively. This works - but for the majority of users, it could work better. So, we've made our automatic batch settings send at a more aggressive speed, having it taper it's speed back, as you come closer to your set quota. 

Expect I<10x speed up> for mass mail sending if you haven't used any of your daily Amazon SES quota. And we're not joking. 


=head2 Bugfixes

=head3 Send a Webpage and Plaintext Messages

Dada Mail's Send a Webpage screen was initially envisioned to send out HTML-formated mailing list messages fetched via a URL. Users have said that they would like to use the same functionality to send PlainText-formatted 
messages. But when they try, Dada Mail complains about a missing HTML version of the webpage.

Dada Mail should now have proper support to explicitly NOT set an HTML version of a message, as well as the ability to correctly send a PlainText version of a message, without requiring an HTML version. 

Setting a Plainted scheduled message with the Send a Webpage screen will also work correctly. Dada Mail should correctly sense if the PlainText version has been modified since the last mass mailing has been sent, and 
skip over a scheduled mass mailing (if you have set things up to do so).

=head3 Quoted Replies not formatted correctly in public archives

Discussion messages usually show some, or all of the original message they're replying to. Dada Mail  formats this reply, so that it's easier to distiguish the reply, from the original message - just like your mail 
reader. This functionality seems to have been missing in v9 of Dada Mail, as the needed style was removed. 

We've changed this functionality, so that quoted text shown in the public archives are simply wrapped in blockquote HTML tags. 

=head3 File Attachments

In certain situations, file attachments were not properly being sent with mass mailings. We've done some work to ameliorate this problem. This problem may be related to the updated version of the Core 5 Filemanager that we ship with Dada Mail, and how it handles handing back the name of the file you have uploaded and selected. 

=head3 Admin login if no mailing lists are public

If all your mailing lists are private, the admin screen shows NO popup menu to select your list, as well as a button labeled, "More..." that you can press to get a textbox to enter in your list shortname. This is silly. 

Now, if the above scenario is in place, you'll see a textbox.

=head3 SQL Options in Dada Mail Installer when SQL is not available

Dada Mail requires the Perl driver for the SQL backed you would like to use. If none are available, the included Installer will simply not show any options, which will confuse the user into thinking that no backend configuration is needed, rather than perhaps allude to the fact that one of those required drivers needs to be separately installed. This should now be fixed. 

=head3 Caching of js and css files

Browsers love to cache files, like cascading style sheets and javascript files. 

This is usually a very good idea! But, some users have been having trouble when upgrading Dada Mail, as the browser is using older versions of these files, breaking their just-upgraded Dada Mail. To help this problem, we're adding a simple query string to the end of the URLs for .css and .js files (that aren't already versioned), so that cache-hungry browser will use a new version of the file, when a user upgrades their Dada Mail. 

=head1 9.0.0

Initial release of v9. Hurray! 

This release introduces a new visual look, feel, and functionality to Dada Mail's Front End, thanks to the utilization of the Zurb Foundation Front End Framework: 

L<http://foundation.zurb.com/>

Big wins to using the Foundation Framework are: 

=head3 Removal of Crufty HTML

Dada Mail is a mature application, first written in 1999. Some of the HTML used for formatting was still relying on tables. Still! Almost all table-based layouts have now finally been removed, being replaced using Foundation's Grid Layout System: 

L<http://foundation.zurb.com/docs/components/grid.html>

Tables are still used, but usually only for tabular data. 

=head3 Responsive Design

Dada Mail takes full advantage of Foundation's support for Repsonsive Design, especially in the List Control Panel. That means you can more easily and comfortably use Dada Mail on your phone or tablet - the design will adapt to your screen's available real estate. For example: The List Control Panel's top bar menu will be hidden off-canvas if you're viewing on a phone device, but can be revealed via a hamburger menu on the upper left side of the toolbar menu. 

=head3 Todo

At this point, we have not heavily customized Dada Mail's design - the app right now has the same look and feel of the default styling of Foundation.
 Future releases will move towards refining Dada Mail's own design. To do this, we will be utilizing Foundation's SASS workflow: 

L<http://foundation.zurb.com/docs/sass.html>

=head2 Features

=head3 One-Click Unsubscribe

One-Click Unsubscribe has been reintroduced into Dada Mail in a much more secure form, as well as now being smart enough to know when the unsubscribe link has been visted by an actual user or an app that is scanning the received message and then following all links found within.

For the former, unsubscription will truly be one-click. Our technique relies on Javascript - if Javascript is not available, the previous method will be shown: displaying a form for the subscriber to fill out with their email address. 

=head3 Enhanced Mailing List Login Security

Dada Mail now records the IP Address from a successful login. If this IP Address changes through a session, the session will be invalidated, and the user will be required to log in again. 


=cut
