=pod

=encoding utf-8

=head1 10.5.0 (Beta)

=head2 Features

=head3 Rich Filemanager Support 

Dada Mail has come shipped with multiple file managers: KCFinder, and Core5 Filemanger. We're adding a new 
filemanager called, B<Rich Filemanager> (L<https://github.com/servocoder/RichFilemanager>) which will be set as the default. 

Rich Filemanager is an update of Core 5 Filemanager, which has shown a slowdown of development and is listed as, "deprecated" by its developer. 

Rich Filemanager comes with some pretty great features and enhancments over Core 5 Filemanager: 

=over

=item * Drag-and-drop support

=item * Clipboard feature: copy, cut, paste, clear

=item * Multiple & chunked uploads support - based on jQuery-File-Upload

=item * New design of multiple upload window; New upload controls for each previewed file (start, abort, resume, delete, etc.)

=item * Online text / code editor - based on codeMirror

=item * Online PDF & OpenOffice documents viewer - based on viewerJS

=item * Online MS Office documents viewer - based on Google Docs Viewer

=item * Extended list of previewed file types via ViewerJS

=back

and more. 

We are not yet removing support either of the two current file managers, so if you're happy with them, keep using them! 

=head1 10.4.0

=head2 Features

=head3 Drag and Drop File/Image Support in CKEditor! 

We've upgraded the bundled version of CKEditor that comes with Dada Mail to B<v4.6.2>, and
we've implemented the necessary backend component to allow support for dragging and dropping images 
and files right into the rich text editor! Images may also be pasted right into the rich text editor, 
without you needing to save the image to a file beforehand. 

Images (jpg's, png's and gif's) will show up inline; all other supported files 
will be uploaded, and added to your message as a link. Some files, based on their file ending, will not be 
allowed for security reasons. 

Since the backend component of this feature is implemented right in Dada Mail, 
there's no additional setup or configuration required and all security checks are handled
by Dada Mail.  

The included file managers: KCFInder and Core5 Filemanager, are still bundled with Dada Mail 
and can work with these new capabilities. Previously drag-and-dropped files/images can be viewed, selected, 
and reused using either of the file managers. 

By default, images are resized if they're larger than 640px to make the size of your mailing list messages a little 
nicer for your recipients. This option can be enabled/disabled in the list control panel under, B<Mass Mailing: Options>. 
Look for the option labeled, B<Resize drag-and-drop images>. Resizing requires the CPAN Perl Module, C<Image::Resize> and 
can be installed by itself, or by installing the C<Bundle::DadaMail> CPAN Perl Module. 

=head3 Phone numbers! 

You can now add a phone number to your List Information. 
The phone number will appear with the rest of your contact information, 
in the footer of your mass mailings. It's a clickable link, which works well for 
those reading your messages on their mobile device! 

=head3 Redirect links in the modal window

Dada Mail has support to show the results of a subscription in a modal window, using the subscription forms 
in its own screens, or through its jQuery plugin subscription forms. 
Dada Mail also has support for redirect your users to a custom page once their done, say, 
filling out the subscription form. Wouldn't it be great to combine the two? Show the custom URL in the modal window. 
Now, Dada Mail can do exactly that. Look for these options in the list control panel under, B<Mailing List:Options> 
- there's a few places custom redirect URL's can be used. Where this new feature is supported, you'll also see the following option, 
B<Show the URL instead in a modal window, if that's being used> 

=head2 Bugfixes

=head3 Mailing List Password Reset Broken

L<https://github.com/justingit/dada-mail/issues/640>

=head1 10.3.6

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.3.5 release of Dada Mail. 

=head2 Bugfixes

=head3 Mailing List Message Theme templates only use "default"'s stylesheet when styling the message body itself 

L<https://github.com/justingit/dada-mail/issues/638>

=head1 10.3.5

=head2 Features

=head3 Youtube link added

Along with a Facebook Page, Twitter URL, and Google+ URL, you can now set a Youtube link

=head1 10.3.4

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.3.4 release of Dada Mail. 

=head2 Documenation Updates 

Several of the included docs have been refreshed significantly, including: 

=head3 Google reCAPTCHA v2 Support

L<http://dadamailproject.com/d/features-CAPTCHA.pod.html> 

=head3 Amazon SES Third Party Email Sending Support

L<http://dadamailproject.com/d/features-amazon_ses_support.pod.html> 

=head3 Installing CPAN Perl Modules

L<http://dadamailproject.com/d/FAQ-installing_CPAN_Perl_modules.pod.html> 
 
 =head2 Bugfixes

=head3 Error in Profile.pm #636 

L<https://github.com/justingit/dada-mail/issues/636>

=head3  Plugins - Bridge: Moderation Reject Message, Message label spam email notifications never get sent #634 

L<https://github.com/justingit/dada-mail/issues/634>

=head3 Resend Confirmation Email: Fails if email contains "+" (character is stripped from address). #633 

L<https://github.com/justingit/dada-mail/issues/633>

=head3 Dada Mail complains of unverified addresses if SES SMTP gateway is used, but no SES keys are added #637 

L<https://github.com/justingit/dada-mail/issues/637> 

=head1 10.3.3

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.3.2 release of Dada Mail. 

This release also refreshes and clarifies the install process and the documentation that goes with it. 

=head2 Bugfixes

=head3 Extensions: multiple_subscribe.cgi does not work with Google reCAPTCHA correctly #631

L<https://github.com/justingit/dada-mail/issues/631> 

=head3 Link/Button in public archived message does not work - goes to, "http://dancingindigochild.local/"? #632

L<https://github.com/justingit/dada-mail/issues/632> 

=head1 10.3.2

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.3.1 release of Dada Mail. 

=head2 Bugfixes

=head3  Google reCAPTCHA compatibility/configuration check returns false positive #630 

L<https://github.com/justingit/dada-mail/issues/630>

=head1 10.3.1

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.3.0 release of Dada Mail. 

=head2 Bugfixes

=head3 Google reCAPTCHA code not shown at all/shown for every profile field for Minimal Subscription Form #627

L<https://github.com/justingit/dada-mail/issues/627>

=head3 Plugins: Bridge Discussion Lists do not work if Google reCAPTCHA is enabled for the initial sign up form #628

L<https://github.com/justingit/dada-mail/issues/628>

=head3 Bounce Handler: modal window does not show history of bounces, but message, "plugin not registered" #626

L<https://github.com/justingit/dada-mail/issues/626>

=head1 10.3.0

=head2 Features

=head3 Mass Mailing Message from RSS Feed

Dada Mail can transform a RSS Feed into an email message to tbe sent as a mass mailing. Read how to work with this in the following article:

L<http://blog.dadamailproject.com/2017/01/03/use-dada-mail-to-create-a-mass-mailing-from-a-blog-feed-then-send-it-on-a-recurring-schedule/>

Find this option in the list control panel under, 

I<Mass Mailing - Send a Webpage> 

In the I<HTML Version> tab, click the option, 

I<Grab content from an RSS/Atom feed>

and enter the URL of the feed in the textbox below this radio button. Additional options are available, 
including adding HTML content before and after the entries from the feed, setting how many entries are included in the message, 
and if the full entry is included or just a summary should be used. 

Sending content from a feed becomes very powerful, when set up to send on a recurring schedule. If the option, 

I<Only send the next scheduled mass mailing, if the primary content differs from the previous scheduled mass mailing>

is checked, only newer entries that have not already been sent will be included in future mass mailings. 




=head1 10.2.4

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.2.3 release of Dada Mail. 

=head2 Bugfixes

=head3 Attachments in archived messages with encoded filenames cannot be downloaded #623

L<https://github.com/justingit/dada-mail/issues/623>

=head3  List owner Receives copy of invitation message (with broken invitation link) #624 

L<https://github.com/justingit/dada-mail/issues/624>

=head3  API bug in Mass Mailings Sent by Schedules and Webservices #625 

L<https://github.com/justingit/dada-mail/issues/625>

=head1 10.2.3

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.2.2 release of Dada Mail. 

=head2 Bugfixes

=head3 Switching lists when working on a draft causes Server Error #621

L<https://github.com/justingit/dada-mail/issues/621>

=head3  Filenames in attachments are not properly encoded #602 

L<https://github.com/justingit/dada-mail/issues/602>

=head1 10.2.2

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.2.1 release of Dada Mail. 

=head2 Bugfixes

=head3  No default subject is set in Send a Message or Send a URL screens #618 

L<https://github.com/justingit/dada-mail/issues/618>

=head3 Characters in the Subject header of the, "mass mailing finished notification" may be garbled. #619

L<https://github.com/justingit/dada-mail/issues/619>

=head3 "Forward to a Friend" DMARC issues #613 

L<https://github.com/justingit/dada-mail/issues/613>

=head3 Encoding Issues with HTML Message Body in Send a Message screen #610

L<https://github.com/justingit/dada-mail/issues/610>

=head1 10.2.1

=head2 Focus

This is mostly a bug-fix release for issues found in the v10.2.0 release of Dada Mail. 

=head2 Bugfixes

=head3 Subject wrongly encoded in Drafts/Stationery/Schedules screen #614

L<https://github.com/justingit/dada-mail/issues/614>

=head3 Google reCAPTCHA fails on signup form in certain situations #615 

L<https://github.com/justingit/dada-mail/issues/615>

=head3 Membership: View Screen hides buttons in Safari browser #616 

L<https://github.com/justingit/dada-mail/issues/616>


=head1 10.2.0

=head2 Focus

We've added support for showing a B<CAPTCHA on the initial signup form!> 

See the post about this feature for more details: 

L<http://blog.dadamailproject.com/2016/12/06/add-google-recaptcha-on-dada-mail-subscription-forms/>

as well as the docs on advanced installation configuration, 

L<http://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html#Configure-CAPTCHA>

We've also removed support for reCAPTCHA v1, and the Default CAPTCHA type. You're
so much better served with reCAPTCHA v2, that these other choices just aren't worth your time. 

reCAPTCHA v2 requires the following CPAN module: C<Google::reCAPTCHA>, which you can install on its own, 
or through our, C<Bundle::DadaMail> module, which will install all the other optional CPAN modules Dada Mail
takes advantage of. Here's how you install CPAN modules, 

L<http://dadamailproject.com/support/documentation-10_1_0/FAQ-installing_CPAN_Perl_modules.pod.html>

=head1 10.1.0

=head2 Focus 

B<Themes!> Dada Mail now comes with 10+ new themes, to complement the Default theme that first 
shipped with v10.0.0. Themes can be selected per mailing list in, B<Appearance: Email Themes>. 
A preview of the selected theme will be shown below the form on this screen. 

=head1 10.0.3

=head2 Focus 

This is mostly a bug-fix release for issues found in v10.0.2 of Dada Mail. 

=head2 Changes 

=head3 Set default layout for mass mailings

This is a small feature, but could be useful for people who normally send messages using Bridge, but want to 
use a layout that's not the default (Full) layout. 
Now, you may set which template is used by default, on allyour mass mailings. 
Look in the B<Mass Mailing: Options> screen for the option to set this up under, B< Default Mass Mailing Layout>

=head3 Work on Scheduled Tasks

This release has more work on scheduled tasks, and making sure that they're not run concurrently, 
which could cause the tasks needed to be done, done two or more times. There's also work on quashig any
 race conditions that could potentially happen. 
This work is a continuation of the work described below under, B<Bridge, Lock Files, and zombie processes>. 

=head1 10.0.2

This is mostly a bug-fix release for issues found in v10.0.1 of Dada Mail. 

=head2 Changes

=head3 New Option for HTML Email Messages: Embed of Link Images

By default, all images in an HTML message are attached and embedded within the email message itself. 

This can lead to large email messages, so we've added a new option to simply link to these images instead. 
Look for the option in the List Control Panel under, B<Mass Mailing: Options>. 
This will affect all email messages sent out from a mailing list, 
not just messages sent out in a mass mailing. 

=head3 Content-Disposition header added to embeded image attachments

Related to the abov change, the C<Content-Disposition> header appears to have been missing from the 
MIME part that relates to the attached images. 
This may cause the embedded image to show up by itself at the end of a message, depending on your mail reader. 
We hope the iclusion of this header will stop this from happenig in most mail readers. 

=head3 Bridge, Lock Files, and zombie processes

This is a big one, if you are running discussion mailing lists. 
We've made a few changes, to help make running multiple mailing lists with Bridge a lot smoother. 

The first change we've made is making sure the lockfile created is specifically named for the mailing list being worked on. 
In the past, the SAME lockfile was used for all mailing lists, 
so if there was a problem with one mailing list, 
the next mailing list worked on may not be successful, because the lock was still "live", basically. 
Bridge would also not unlock the lockfile if there was say, a error with logging into the POP3 server, 
causing problems on additional runs of the plugin. 
This may culminate into zombie processes of Dada Mail, as well as perhaps even the POP3 daemon, which may have a connection kept open by a zombie process. 
All of this isn't good stuff, and we hope to have cleared out this problem. 

If you're experiencing zombie processes, and you're running mailing lists with Bridge enabled, these above issues may be affecting you. 
Upgrading could help you out, immensely. 

=head3 Javascript Scrubber Disabled

For the time being, the Javascript scrubber for Dada Mail has been disabled, 
as it also breaks HTML links that have template tags embedded within them. 

=head1 10.0.1

=head2 Focus 

This is mostly a bug-fix release for issues found in v10.0.0 of Dada Mail. 

=head2 Bugfixes

=head3  Data in Email Templates not properly UTF-8 Decoded

L<https://github.com/justingit/dada-mail/issues/604>

=head3 Previews do not work on upgraded Dada Mails, because the table previews are stored is never created 

L<https://github.com/justingit/dada-mail/issues/606>

=head3  Schedule and Stationary screens do not have Preview button

L<https://github.com/justingit/dada-mail/issues/605>

=head3 Using Preview with no content gives no results

L<https://github.com/justingit/dada-mail/issues/603>


=head1 10.0.0

=head2 Features

=head3 Enhanced Email Messages

=head4 Powered by Foundation for Emails

Foundation for Emails (L<http://foundation.zurb.com/emails.html>) is a framework to develop HTML email messages that, "I<Sucks Less>": they're beautiful, responsive, and look correctly in most HTML-capable email readers - even Outlook! 

Work with these HTML emails via Sass Workflow:

L<https://foundation.zurb.com/emails/docs/sass-guide.html>

Dada Mail's quiver of HTML email templates has been turned into its own Github project: 

L<https://github.com/justingit/dada_mail_foundation_email_templates>

which you may use as a starter for your own customized email templates for Dada Mail:

L<http://dadamailproject.com/d/features-email_themes.pod.html>

=head4 Email Themes

Dada Mail now has support for B<Email Themes>: collections of email templates that you may use to customize the look and feel of your email messages. 

Currently, Dada Mail comes with one email theme and supports additional custom themes.

=head4 Mass Mailing Email Layouts

Email Themes include the ability to choose a specific layout for your mass mailing to be wrapped up in. 

Currently, the following layouts are available: 

=over

=item * Full Layout

=item * Minimal Layout

=item * For Discussion List Messages

=item * Don't use a Layout 

=back

=head4 Mass Mailing Preview

Without needing to send a test message out, you may now preview how your mass mailing will look, right in the Send a Message screen. This makes it easy to try different layouts and other options out, before comitting to sending to your entire mailing list. 

=head4 Preheader support 

Set a B<Preheader> for your mass mailings in the Send a Message and Send a Webpage screens. Use the preheader to summarize, preview, and entice subscribers into reading the rest of your message. 

=head4 Set a logo image as well as social network links in your email messages

The newly improved HTML email messages also support showing a logo, and list social media likns - these all can be set 
under B<Mailing List - List Information>

=cut