=pod

=encoding utf-8

=head1 Dada Mail Changelog for v9.x

=head1 9.0.0

Initial release of v9. Hurray! 

This release introduces a new visual look, feel, and functionality to Dada Mail's Front End, thanks to the utilization of the Zurb Foundation Front End Framework: 

L<http://foundation.zurb.com/>

Big wins to using the Foundation Framework are: 

=head3 Removal of Crufty HTML

Dada Mail is a mature application, first written in 1999. Some of the HTML used for formatting was still relying on tables. Still! Almost all table-based layouts have now finally been removed, being replaced using Foundation's Grid Layout System: 

L<http://foundation.zurb.com/docs/components/grid.html>

Tables are still used, but usually only for tabular data. 

=head3 Responsive Design

Dada Mail takes full advantage of Foundation's support for Repsonsive Design, especially in the List Control Panel. That means you can more easily and comfortably use Dada Mail on your phone or tablet - the design will adapt to your screen's available real estate. For example: The List Control Panel's top bar menu will be hidden off-canvas if you're viewing on a phone device, but can be revealed via a hamburger menu on the upper left side of the toolbar menu. 

=head3 Todo

At this point, we have not heavily customized Dada Mail's design - the app right now has the same look and feel of the default styling of Foundation.
 Future releases will move towards refining Dada Mail's own design. To do this, we will be utilizing Foundation's SASS workflow: 

L<http://foundation.zurb.com/docs/sass.html>

=head2 Features

=head3 One-Click Unsubscribe

One-Click Unsubscribe has been reintroduced into Dada Mail in a much more secure form, as well as now being smart enough to know when the unsubscribe link has been visted by an actual user or an app that is scanning the received message and then following all links found within.

For the former, unsubscription will truly be one-click. Our technique relies on Javascript - if Javascript is not available, the previous method will be shown: displaying a form for the subscriber to fill out with their email address. 

=head3 Enhanced Mailing List Login Security

Dada Mail now records the IP Address from a successful login. If this IP Address changes through a session, the session will be invalidated, and the user will be required to log in again. 


=cut
