

=pod

=head1 CPAN Modules in Dada Mail 

Dada Mail takes advantage of several CPAN Modules to get the dirty work done. 

If you're concerned about what Modules are installed here's the list: 

	CGI:
		Apache.pm
		Carp.pm
		Cookie.pm
		Fast.pm
		Pretty.pm
		Push.pm
		Switch.pm
		Util.pm
	CGI.pm
	Crypt:
		CipherSaber.pm
	Email:
		Valid.pm
	HTML:
		FromText.pm
		Template.pm
	Mail:
		Address.pm
		Bulkmail:
			DadaMailServer.pm
			DummyServer.pm
			Dynamic.pm
			Object.pm
			Server.pm
		Bulkmail.pm
		Cap.pm
		Field:
			AddrList.pm
			Date.pm
		Field.pm
		Filter.pm
		Header.pm
		Internet.pm
		Mailer:
			qmail.pm
			rfc822.pm
			sendmail.pm
			smtp.pm
			test.pm
		Mailer.pm
		Send.pm
		Util.pm
	MIME:
		Lite:
			HTML.pm
		Lite.pm
		Type.pm
		Types.pm
	MLDBM:
		Serializer:
			Data:
				Dumper.pm
			FreezeThaw.pm
			Storable.pm
	MLDBM.pm
	Net:
		Cmd.pm
		Config.pm
		DNS:
			Header.pm
			Nameserver.pm
			Packet.pm
			Question.pm
			Resolver.pm
			RR:
				A.pm
				AAAA.pm
				AFSDB.pm
				CERT.pm
				CNAME.pm
				DNAME.pm
				EID.pm
				HINFO.pm
				ISDN.pm
				LOC.pm
				MB.pm
				MG.pm
				MINFO.pm
				MR.pm
				MX.pm
				NAPTR.pm
				NIMLOC.pm
				NS.pm
				NSAP.pm
				NULL.pm
				OPT.pm
				PTR.pm
				PX.pm
				RP.pm
				RT.pm
				SOA.pm
				SRV.pm
				TSIG.pm
				TXT.pm
				X25.pm
			RR.pm
			Select.pm
			Update.pm
		DNS.pm
		POP3.pm
		SMTP.pm
	Text:
		Tabs.pm
		Wrap.pm


If you want to use the version of these modules that are located in your site-wide Perl directory, 
just don't upload these files. 


=cut

