=pod

=head1 Upgrading Dada Mail 3.0.x to Dada Mail 3.1

=head1 Background

=head1 .dada_config changes

=head2 %SQL_PARAMS

%SQL_PARAMS in .dada_config for 3.0.x: 

	%SQL_PARAMS = ( 

		# May just be, "localhost" 
		dbserver         => 'localhost',
		
		database         => '',
	
		# MySQL:      3306
		# PostgreSQL: 5432      
		port             => '3306',
	
		# MySQL:      mysql 
		# PostgreSQL: Pg
		# SQLite:     SQLite
		dbtype           => 'mysql',  
	
		user             => '',          
		pass             => '',

		subscriber_table    => 'dada_subscribers',
		archives_table      => 'dada_archives', 
		settings_table      => 'dada_settings', 
		session_table       => 'dada_sessions', 
		bounce_scores_table => 'dada_bounce_scores', 

	);


%SQL_PARAMS in .dada_config for 3.1: 

	%SQL_PARAMS = ( 

		# May just be, "localhost" 
		dbserver         => 'localhost',
		
		database         => '',
	
		# MySQL:      3306
		# PostgreSQL: 5432      
		port             => '3306',
	
		# MySQL:      mysql 
		# PostgreSQL: Pg
		# SQLite:     SQLite
		dbtype           => 'mysql',  
	
		user             => '',          
		pass             => '',

		subscriber_table                => 'dada_subscribers',
		profile_table                   => 'dada_profile', 
		profile_fields_table 	        => 'dada_profile_fields', 
		profile_fields_attributes_table => 'dada_profile_fields_attributes',
		archives_table                  => 'dada_archives', 
		settings_table                  => 'dada_settings', 
		session_table                   => 'dada_sessions', 
		bounce_scores_table             => 'dada_bounce_scores', 
		clickthrough_urls_table         => 'dada_clickthrough_urls',

	);

New lines: 

		profile_table                   => 'dada_profile', 
		profile_fields_table 	        => 'dada_profile_fields', 
		profile_fields_attributes_table => 'dada_profile_fields_attributes',
		clickthrough_urls_table         => 'dada_clickthrough_urls',

If you DO NOT put these lines in your .dada_config file, Dada Mail will attempt to massage your configuration to work, anyways. 

=head1 New SQL Tables to Create

If you do not want to create the new SQL Tables and change the schema of the old SQL tables, we suggest
using our own 3.0 to 3.1 migration tool. More information: 

L<http://dadamailproject.com/support/documentation/dada_3_to_dada_3.1_sql.pl>

We suggest using the migration tools ourselves. 

Make the following tables: 

=over

=item * dada_profile

=item * dada_profile_fields

=item * dada_profile_fields_attributes

=item * dada_clickthrough_urls

=back

=head2 New Schemas

The Schemas for each database/table is located in the dada/extras/SQL directory of the distribution. 

For the exception of the, C<dada_subscribers> table, all previous table schemas are essentially the same. 

Subscriber Profile Fields information that once used to live in the C<dada_subscribers> table, now lives in the C<dada_profile_fields> table. The migration tool mentioned above will move that information from where it was, to where it has to go. 

=head2 $CLICKTHROUGH_DB_TYPE

The new C<dada_clickthrough_urls> table holds the URL redirects for the clickthrough tracker. 

=head1 New Template Variables in the List Template (default_list_template.tmpl)

=over

=item * show_profile_widget

=item * profile_widget

=item * subscribed_to_list

=back

=head1 $PROFILE Variables

=over

=item * $PROFILE_ENABLED

=item * $PROFILE_EMAIL

=item * $PROFILE_ENABLE_CAPTCHA

=item * $PROFILE_ENABLE_MAGIC_SUBSCRIPTION_FORMS

=item * $PROFILE_COOKIE_PARAMS

=item * $PROFILE_GRAVATAR_OPTIONS

=back

=cut
