=pod 

=encoding utf-8

=head1 Installing CPAN Perl Modules

Many of Dada Mail's most advanced features rely on additional code libraries, called B<CPAN Perl Modules> to be installed and available on the web server that Dada Mail runs on. 
These features are usually entirely optional, meaning Dada Mail will run just fine without them, but your experience will be greatly enhanced if they are available. 

Usually, if a feature is unavailable because of a missing CPAN Perl module: there will be an alert either in the included Dada Mail Installer where you would initially configure this feature; or from within the list control panel, where you would enable/work the feature. 

Dada Mail does already ship with many included CPAN Perl modules, but it can't ship with all of them, as they could potentially need additional configuration, a dependency outside of Dada Mail's or Perl's immediate ecosystem, or code compilation. 

A list of these optional modules to install can be found in the C<Bundle::DadaMail> module: 

L<https://metacpan.org/pod/Bundle::DadaMail

A fairly exhaustive list of all the CPAN Perl Modules Dada Mail ships with can be found in the, C<Bundle::DadaMailXXL> module:

L<https://metacpan.org/pod/Bundle::DadaMailXXL>

In this FAQ, we're going to focus on using the cPanel Perl Module Installer, which may be available to you, if you're running a hosting account powered by cPanel.  

=head1 Using the cPanel Perl Module Installer to install Bundle::DadaMail

We're going to go ahead and install C<Bundle::DadaMail> which will give us all 
the optional modules that Dada Mail uses. 

Log into your cPanel. Search for, B<Perl Modules> 

=begin html

<p style="text-align:center">
<img src="http://dadamailproject.com/images/support/documentation/v10/cpan/cpan-cpanel-perl_modules.jpg" width="1024" height="597" style="border:1px solid black" /><br /> 
<em>Perl Modules</em> 
</p>

=end html

Click this icon. 

Scroll down, and find the form labeled, B<Install a Perl Module>.  In this form field, type in: C<Bundle::DadaMail>, then click: B<Install Now>


=begin html

<p style="text-align:center">
<img src="http://dadamailproject.com/images/support/documentation/v10/cpan/cpan-install_a_module.jpg" width="1024" height="189" style="border:1px solid black" /><br /> 
<em>Install a Module</em> 
</p>

=end html

The process of fetching the module and installing it will then commence. Prepare to wait a few minutes, as the process does take a little time. 

A lot of diagnostics will be printed out, much of which you may ignore, unless the install doesn't work correctly. One reason the installation of a module will fail is because a compiler is not available. If you're on a shared host, you may be out of luck, unless your hosting support can help. If you have more control over your account, like access to WHM, you can turn on complier support in there. 

Once the process is completed, click the button labeled, B<Go Back> at the bottom of the screen (or generally: go back to the B<Perl Modules> screen), and scroll below the, B<Install a Perl Module> form, where the table of B<Installed Perl Module(s)> is located. It should now be populated with many of the different Perl modules Dada Mail can now use. 

=head1 Other ways to install CPAN Perl Modules

If you're not, you may have to ask your hosting support to install these modules. If you have full access to your webserver, the traditional ways of installing CPAN Perl modules will work just fine for you - either using a package manager released by the vendor of your operating system, or by using the C<cpan> or C<cpanm> command line tools. It's a little trickier, but certainly not impossible, to install Perl module without root privileges, but you'll need access to your account via the command line. 

Some resources: 

L<http://perl-begin.org/topics/cpan/life-with-cpan/non-root/>

L<https://github.com/miyagawa/cpanminus>

L<http://stackoverflow.com/questions/2980297/how-can-i-use-cpan-as-a-non-root-user>


=cut
