=pod

=head1 Twitter Support in Dada Mail 


=head1 Introduction

Yes, it's true, Dada Mail can Tweet. 

=head1 Status - Experimental! 

This feature is quite new in Dada Mail and experimental. Have fun with it! 

=head1 Requirements 

Twitter support ships in Dada Mail, 3.1, but you will need additional perl CPAN modules installed to have the functionality be enabled. The additional CPAN modules you'll need are: 

=over

=item * Net::Twitter::Lite;

http://search.cpan.org/~mmims/Net-Twitter-Lite

=item * WWW::Shorten

http://search.cpan.org/~davecross/WWW-Shorten/

=back

=head1 Enabling

It can be enabled on a per-list basis in the list control panel under, 

Manage List - Sending Options
 
Look for the fieldset labeled, "Twitter". 

=head1 Using 

Dada Mail will automatically Tweet the Subject of your message, as well a link  to the archived message, every time you send a mass mailing out, either via the, "Send a Message", "Send a Webpage" screens or through Dada Bridge. 

=head1 Feedback

This is a new, experimental feature and we'd like feedback on how it's working for everyone. Let us know!

=cut
