=pod

=head1 Subscriber Profile Fields

=head1 Implementation

The extra Subscriber Profile Fields in Dada Mail are saved in the C<dada_profiles> table. Right now, there's a limit of 100 extra columns and each column is given the data type of, C<text>. 

=head1 Requirements

The Subscriber Profile Fields feature in Dada Mail requires that you use one of the supporting SQL backends. Currently, Dada Mail supports B<MySQL>, B<Postgres> and B<SQLite>. 

=head1 Downgrading

Most likely, if you ever have to I<downgrade> Dada Mail, these extra fields shouldn't hurt too much to keep around. From my tests, Dada Mail will simply just ignore the extra fields. 

=head1 Using 

=head2 Adding a New Subscriber Field

Adding a new subscriber field is pretty easy. Log into the list control panel B<with the Dada Mail Root Password> (very important) to any list. On the left hand menu, under, B<Profiles>, click, B<Profile Fields>

This screen will allow you to add/remove the Subscriber Profile Fields. This screen will also let you set a fallback value. The fallback value is used in mailmerging and is used as the value fo the field tag when no value is present. 

The fallback value is saved in the dada_settings table in the B<fallback_field_values> setting. 

Please note that removing any Subscriber Profile Fields will B<permanently delete all the information that once was saved in this particular field for ALL Mailing Lists>. 

The other thing to note is that Subscriber Profile Fields are B<GLOBAL>, meaning, they'll be there for each Mailing List that Dada Mail manages. 

You can also add a subscriber field in Dada Mail by just adding a new column to the dada_subscribers table yourself via SQL. I would be careful doing so, since you'll curcumvent any checks that are done via the list control panel, but you're open to and Dada Mail will see your new columns as new subscription fields.

=head2 Mail Merging

Mail Merging in Dada Mail in mailing list messages using your new Subscriber Profile Fields is pretty easy: 

Say you have a field named, B<first_name>. To use the value of the saved field in an email message, you'd write the field as a tag, like this: B<E<lt>!-- tmpl_var subscriber.first_name --E<gt>>. It would look like this in your actual message: 

 Hello, <!-- tmpl_var subscriber.first_name -->
 
      It's really nice to talk to you!
      
  -- Me.


Mail Merging works for almost every single type of email message Dada Mail can send out. 

=head2 Partial List Sending

You can now make a query on your subscription list to send to only part of your mailing list. For example, if you have a field named, "city", you can tell Dada Mail, "only send to people whose, "city"  value is set to, 'Denver'. 

Currently, this is done in the, "Send a Message" and, "Send a Webpage" screens. Click the, B< Show/Hide Partial Sending Options>. You'll be presented with a form that allows you to make simple queries and give you a preview of who's going to the message. 

=head2 Subscriptions

The subscription process is similar to previous versions of the program, except that the subscription form now supports capturing any Subscriber Profile Fields present. 

Currently, all subscription fields will be shown, except (by default), Subscriber Profile Fields that are prefixed with an underscore ("_"). For example, the field, 

 first_name

Will be shown! The field, 

 _secret_field

Will not. Consult the Config.pm file for how to set the special prefix.  

Currently, all the subscription fields are optional, except the email address. 

You may acquire the HTML code needed to embed the subscription form in a webpage in the usual location: B<Under Manage Appearance>, click on, B<Subscription Form HTML>. 

There's also a new option to embed a javascript call that will create the HTML form for you. This is beneficial, since the subscription form on your webpage will automatically update, if you add/remove a form field. 

There are a few difference internally with the subscription process. The largest is that all subscription requests by users will first have the subscriber information saved in the, "sub_confirm" sublist. This is where the information filled out in your subscription form is saved, before a subscription is confirmed. Once a subscription is confirmed, the information is moved to the main, "list" sublist. 

A similar scenario takes place for unsubscriptons: The subscriber is first put on a, "unsub_confirm" sublist and is taken off this list, as well as the main, "list" sublist once the confirmation process is completed. 

Because of this, you will no longer be able to use complete confirmaton URLS, (URLS that have the pin number and email address embeded in the URL) in any place other than in the subscription and unsubscription confirmation email messages.

=head2 The Subscription Form Template

Every single instance of the subscription form is handled by one template file, living in the dada/DADA/Template/templates directory called, C<subscription_form_widget.tmpl>. Changes to this file will affect every instance of the subscription form in the program. 

=head2 Importing Subscribers

The file type you need to import your subscribers in must be in CSV format. The order of the fields in that CSV format should be displayed at the top of the screen. 

=head2 Editing Individual Subscriber Information

You can edit an individual's subscriber information in the list control. Under, B<Your Subscribers>, click on, B<View>. You'll be presented with a table of your subscribers, with all their subscription information. Clicking on the email address of the subscriber will bring you to a screen to edit the subscription information. Pretty simple. 

=head1 See Also

=head2 Technical Documentation 

=head3 Subscriber Backend

=head4 DADA::MailingList::Subscribers

L<http://dadamailproject.com/support/documentation/MailingList_Subscribers.pm.html>

=head3 Profiles 

=head4 Dada::Profile

L<http://dadamailproject.com/support/documentation/Profile.pm.html>

=head4 DADA::Profile::Fields

L<http://dadamailproject.com/support/documentation/Profile_Fields.pm.html>

=head4 DADA::Profile::Session

L<http://dadamailproject.com/support/documentation/Profile_Session.pm.html>

=head4 DADA::ProfileFieldsManager

L<http://dadamailproject.com/support/documentation/ProfileFieldsManager.pm.html>

=head3 Templating System

The HTML Screen and Email Template parts of Dada Mail all use the same system. See: 

L<http://dadamailproject.com/support/documentation/Template_Widgets.pm.html#screen>

And also: 

L<http://dadamailproject.com/support/documentation/App_FormatMessages.pm.html#email_template>

=cut
