=pod

=head1 Scheduled Mass Mailings

Dada Mail supports both single and recurring scheduled mass mailings.

You can create a scheduled mass mailing in the Send a Message, or Send a Webpage screens. Create your message, and when you're ready, click the button labeled, B<Save as: Schedule>. Scheduled Mass Mailings can also be created from Stationery or a Draft Message.

Your schedule will then be saved, the screen will refresh, and options to activate the schedule, as well as options to set a date and time of your schedule will be shown. 

=head1 Options

=head2 Activate

Check the option when you're ready to have your scheduled mailing go live. If a scheduled mass mailing is not activated, it will not be sent out.

=head2 Single

A single scheduled mass mailing will be sent only once, sometime in the future. Click the textbox next to the label, B<Schedule For:> to set the date and time you would like the schedule to go out. A calendar widget should pop up, to facilitate setting up the scheduled date and time.

Once everything is all set, click the button labeled, B<Save Schedule>

=head2 Recurring

A recurring mass mailing will be sent repeatedly, based on the options you've set. You will have to set a start date, and an end date, a time in the day the schedule should go out, and what day you would like it to be sent out on. 

=head3  Starting on: 

This is your starting date. Select the year, month and day you would like your scheduled mass mailings to start. 

=head3  Ending on: 

This is your ending date. Select the year, month and day you would like your scheduled mass mailings to end. 

=head3 At: 

This is the hour, minute, and second your mass mailing will go out at. 

=head3 Sent on: 

Select the days in the week you would like your mass mailing to be sent on. 

=head2 Scheduled Mailing Date/Time Preview

Below the options to set the details of the schedule, will be a box showing you the details of the schedule you're setting. This box will also show the current server time as well as the last time the mass mailing schedules will last checked. 

This box will also shown any reports of problems with the paramaters of your scheduled mass mailing. 

=head2 Save your scheduled mass mailing

Once you've activated your schedule, set the type of schedule you want to send, select the date and times it should go out, save your schedule by clicking the button labeled, B<Save Schedule>

=head2 Viewing/Editing Saved Scheduled Mass Mailing

Once a schedule is saved, you may view and edit them in the list control panel under, B<Mass Mailing - Drafts/Stationery/Schedules>. Click the, B<Schedules> tab to see all your schedules. Click the Subject of your schedule, or click the button labeled, B<Edit...> to further edit your scheduled mass mailing.

=head2 Checking the Scheduled Mass Mailings

Dada Mail's system-wide cronjob checks and runs the scheduled mass mailings. Make sure it's set, or your scheduled mass mailings will not go out: 

L<http://dadamailproject.com/d/features-scheduled_cronjobs.pod.html>

You may manually check the Scheduled Jobs in the list control panel under, B<App Information - Scheduled Jobs> 

=head1 System Requirements

Single Mass Mailing Schedules do not have any unique system requirements. 

Recurring Mass Mailing Schedules require the following CPAN Perl Modules: 

=over

=item * DateTime;

=item * DateTime::Event::Recurrence;

=back

These modules can be installed in a variety of ways: 

L<http://dadamailproject.com/d/FAQ-general.pod.html#How-do-you-install-CPAN-Perl-Modules>

=cut

