=pod

=head1 Dada Mail Profiles Overview

Dada Mail Profiles allow subscribers to a Dada Mail list access to their own profile accounts within Dada Mail, where they can view their current subscriptions, update their subscription information (user-editable Subscriber Profile Fields) and also have additional permissions to subscriber-only features of Dada Mail mailing lists (example; archives that are only available to subscribers of a mailing list). 

=head1 Logging into your Dada Mail Profile

A subscriber can log into their profile, by clicking the, I<[Register/Log In]> 
link that's currently on the top right of the Dada Mail screen: 

=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/regist_login_link.jpg" /><br /> 
<em>The, [Register/Log In] Link</em> 
</p>

=end html

The Profile Login screen looks like this: 

=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/profile_login_scrn.jpg" /><br /> 
<em>The Profile Login Screen</em> 
</p>

=end html

There are three separate forms: log into a profile, register a new profile and to reset a lost password for a profile.
Once logged in, your subscriber will find themselves in the Profile Home screen: 


=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/profile_logged_in.jpg" /><br /> 
<em>The Profile Home Screen</em> 
</p>

=end html 

From here, your subscribers can edit their own Subscriber Profile Fields, view the lists they're subscribed to and also change their profile password. There's also links to each list's archives and a link to unsubscribe from the list. 

Once logged in, a Dada Mail user can navigate throughout and view their logged in status at the upper right hand side of the screen. 

All the subscription forms in Dada Mail will be auto-filled out with the Dada Mail user's email address and the Subscriber Profile Fields will be hidden (so as not to have the user have to re-type the same information twice) 



=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/default_screen_logged_in.jpg" /><br /> 
<em>The Default Dada Mail screen with a logged in user</em> 
</p>

=end html

And that's the new Dada Mail Profiles features, from a user's point of view. 

=head1 List Administration and New Options with Dada Mail Profiles

Since users can now log into Dada Mail, you can now do some fancy things from within your list, concerning list subscribers. 

For example, there are now options to only allow subscribers to view a list's archive: 

=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/subscriber_only_archives.jpg" /><br /> 
<em>Manage Archives - Archive Options</em> 
</p>

=end html

There's also a new option to skip the closed-loop opt-in system, if a subscriber already has a registered profile: 

=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/skip_sub_if_reg.jpg" /><br /> 
<em>Manage List - Mailing List Options</em> 
</p>

=end html

This is hopefully, just scratching the surface of what can be done with the new Dada Mail Profile functionality. 

=head1 Other Features to Look Out For

=head2 Subscriber Profile Fields

Subscriber Profile Fields can now have, B<Labels>, so you don't have to use the name of your subscriber field as the label for things like the subscription form. 

Subscriber Profile Fields can now also be easily re-ordered: 


=begin html 

<p style="text-align:center">
<img src="http://dadamailproject.com/images/features/profile_fields/subscriber_fields.jpg" /><br /> 
<em>Manage Subscribers - Subsriber Fields</em> 
</p>

=end html

=head1 Dada Mail Profile Options

You can change your Profiles Options in Dada Mail within your C<.dada_config> file. 

First, find the following lines in your C<.dada_config> file: 

	=cut
	# start cut for Dada Mail Profile Options

	$PROFILE_OPTIONS = { 
		
		enabled                         => 1, 
		profile_email                   => '', 
		enable_captcha                  => 1, 
		enable_magic_subscription_forms => 1, 
	
		cookie_params =>
		{ 
			-name    => 'dada_profile',  
			-path    => '/',
			-expires => '+7d',		
		},

		gravatar_options => 
		{
			enable_gravators     => 1, 
			default_gravatar_url => undef,
		},
	};

	=cut
	# end cut for Dada Mail Profile Options

I<(if these lines are not present, you may add them to your .dada_config file)>

Remove the following =cut lines (if present): 

	=cut
	# start cut for Dada Mail Profile Options

	=cut
	# end cut for Dada Mail Profile Options

You can now configure your Profile Options. 

=head2 $PROFILE_OPTIONS

=head3 enabled

Sets whether profiles are enabled, or not. Set to, C<1> to enable, set to C<0> to disable. 

=head3 profile_email

When a registration email or reset password email goes out, it'll go out on behalf of this email address. We highly encourage you to fill out this variable, or these email messages may not be sent out correctly. Example: 

 profile_email => 'me@mydomain.com', 

If Profiles are enabled and this variable is left blank, the list owner email address of one of your mailing lists will be used. 

=head3 enable_captcha

Registration for Dada Mail Profiles can be verified using a CAPTCHA. We recommend this feature, if it's available. Set this variable to, C<1> to enable CAPTCHA in the registration form. 

=head3 enable_magic_subscription_forms

B<Magic> subscription forms are pre-filled out with the subscriber's email address, if they're logged into Dada Mail. To enable this feature, set this variable to, C<1> 

=head3 cookie_params

This variable holds a few options to change the behavior of the session management cookie for Dada Mail Profiles. 

=head3 gravatar_options

Gravatars can also be enabled for Dada Mail Profiles. More information: 

L<http://gravatar.com/> 


=head1 Feedback Needed 

We'd love to hear from you about these new features. Please post your feedback to our boards: 

http://dadamailproject.com/support/boards

our developer mailing list: 

http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dadadev/

Or, send us an email: 

http://dadamailproject.com/contact/


=cut