=pod

=head1 CAPTCHA in Dada Mail

Dada Mail supports B<Google reCAPTCHA v2>

=head2 Setting up Google reCAPTCHA in Dada Mail

=head3 Create a Site and Secret Key Pair

Sign up for the Google reCAPTCHA service at,

L<http://www.google.com/recaptcha/admin>

and create a site and secret key pair for the site you have Dada Mail installed at, as outlined here:

L<https://developers.google.com/recaptcha/docs/start>

Make sure you record both the site and secret key somewhere safe - we'll be using them, later.

=head2 Configure Dada Mail to use Google ReCAPTCHA

Plugging in the site and secret keys, and telling Dada Mail to use Google reCAPTCHA is done in Dada Mail's global configuration. 

The easiest way to work with that is through Dada Mail's included web-based installer, so an install or upgrade would be the perfect time to set all this up. 

You can also drop back into the installer to make these configuration changes: L<http://dadamailproject.com/d/install_dada_mail.pod.html#Making-Additional-Global-Configuration-Changes-using-the-Dada-Mail-Installer>

Once in the installer's configure screen, look for B<Advanced Options>.

This is the section where you can setup the plugins/extensions, as well as many of Dada Mail's more advanced features. If you do not see these options, click the button labeled, B<Show/Hide Advanced Options...>

Next, look for a checkbox labeled, B<Configure CAPTCHA Options>. Check the box, and the CAPTCHA options will be revealed.

Dada Mail supports displaying and verifying a CAPTCHA on the initial subscripion form. Check the box labeled, B<Add CAPTCHA on all subscription forms> to enable this feature. 

Plug in the site key and secret key in the textboxes labeled, B<reCAPTCHA Site key:> and, B<reCAPTCHA Secret key:>

Test to make sure if everything works, by clicking the button labeled, B<Test CAPTCHA Configuration...>. If everything works correctly, you'll be shown a working reCAPTCHA v2 widget


=begin html

<p style="text-align:center">
<img src="http://dadamailproject.com/images/support/documentation/v10/google_recaptcha/google_recaptcha_v2.jpg width="649" height="716" style="border:1px solid black" />
</p>

=end html

=head3 Required Perl CPAN Module?

Dada Mail's Google reCAPTCHA support requires the C<Google::reCAPTCHA> Perl module, which you can install from CPAN. See, L<http://dadamailproject.com/d/FAQ-installing_CPAN_Perl_modules.pod.html>


=head1 Using CAPTCHA in Dada Mail

CAPTCHA may be used for: 

=head2 Subscription Confirmations 

=head3 Enabling

In the list control panel, navigate to: B<Mailing List - Options>, under B<Subscriptions>, check the option labeled, B<Enable CAPTCHA>

=head2 "Forward a Friend"

CAPTCHA protection in the "Forward to a Friend" Form is I<highly suggested>, as this form is easy to spoof. 

In the list control panel, navigate to: B<Archives - Options>. 

Check the option labeled, B<Enable CAPTCHA on the, "Forward to a Friend" Form> 

=head2 Profile Registrations

CAPTCHA protection is available for Dada Mail Profile Registrations.

=head3 Enabling

CAPTCHA for Profile Registrations is enabled by default. If you'd like to I<disable> CAPTCHA, you can do so in the config variable, C<$PROFILE_OPTIONS>

=head1 reCAPTCHA Mailhide

If you're using the reCAPTCHA service, you may also take advantage of reCAPTCHA Mailhide. In Dada Mail, this is used to protect individual email addresses in mailing list archives. Before an email address can be viewed, a CAPTCHA has to be solved. 

=head2 Configuration 

Mailhide can also be configued in the Dada Mail Installer. 

If not already shown, click the button, B<Show/Hide Advanced Options...>, then check the option, B<Configure CAPTCHA Options>. Additional CAPTCHA settings will then be revealed. 

Under, B<reCAPTCHA Mailhide Settings>, enter in your B<reCAPTCHA Mailhide Public Key> and B<reCAPTCHA Mailhide Private Key>, much like you did for your CAPTCHA settings, above. You may create those keys here: 

L<https://www.google.com/recaptcha/admin#mailhide/apikey>

=head2 Enabling

In your list control panel, go to: B<Manage Archives - Advanced Archive Options>, under, B<Email Address Protection> select, B<reCAPTCHA MailHide>.

=head2 Requirements

You may need to separately install the C<Captcha::reCAPTCHA::Mailhide> CPAN Perl module, in order to gain reCAPTCHA Mailhide support. 

=cut
