=pod

=head1 CAPTCHA in Dada Mail

=head2 Configuraton

CAPTCHA can be configured in the included Dada Mail Installer.

If not already shown, click the button, B<Show/Hide Advanced Options...>, then check the option, B<Configure CAPTCHA Options>. Additional CAPTCHA settings will then be revealed. 

Dada Mail currently supports three different CAPTCHA types: the B<Default>, image-based CAPTCHA system (based on, C<GD::SecurityImage>),  B<reCAPTCHA v1> and B<reCAPTCHA v2>. v2 is also known as, No-CAPTCHA CAPTCHA as there's no letters/numbers to type - you just have to select the correct images from a group of images. 

We suggest using B<reCAPTCHA v2>. The B<Default>, image-based CAPTCHA isn't always secure, and B<reCAPTCHA v1> will soon be deprecated. B<reCAPTCHA v2> will also the easiest for your users to use. Below, we will only be going over how to configure B<reCAPTCHA v2>.

If B<reCAPTCHA v2> is not available to be utilized, you may have to separately install the required CPAN Perl Module, called, C<Google::reCAPTCHA>. See installing CPAN modules: 

L<http://dadamailproject.com/d/FAQ-installing_CPAN_Perl_modules.pod.html>

Create a B<reCPATCHA Site key> and B<reCPATCHA Secret key>, 

L<https://developers.google.com/recaptcha/docs/start>

And enter them into the Installer under, B<reCPATCHA Site key> and B<reCPATCHA Secret key>. 

You may test that your setup is working by clicking the button labeled, B<Test CAPTCHA Configuration...>. If you can view the CAPTCHA, your configuration is working. 

=head1 Using CAPTCHA in Dada Mail

CAPTCHA may be used for: 

=head2 Subscription Confirmations 

=head3 Enabling

In the list control panel, navigate to: B<Mailing List - Options>, under B<Subscriptions>, check the option labeled, B<Enable CAPTCHA>

=head2 "Forward a Friend"

CAPTCHA protection in the "Forward to a Friend" Form is I<highly suggested>, as this form is easy to spoof. 

In the list control panel, navigate to: B<Archives - Options>. 

Check the option labeled, B<Enable CAPTCHA on the, "Forward to a Friend" Form> 

=head2 Profile Registrations

CAPTCHA protection is available for Dada Mail Profile Registrations.

=head3 Enabling

CAPTCHA for Profile Registrations is enabled by default. If you'd like to I<disable> CAPTCHA, you can do so in the config variable, C<$PROFILE_OPTIONS>

=head2 CAPTCHA Configuration

CAPTCHA can also be configured directly in your C<.dada_config> file: 

=head3 reCAPTCHA Configuration

Add the following lines to your C<.dada_config> file:

	$CAPTCHA_TYPE     = 'Google_CAPTCHA';
	$RECAPTCHA_PARAMS = { 

	    public_key     => undef,
	    private_key    => undef,

	};

=head1 reCAPTCHA Mailhide

If you're using the reCAPTCHA service, you may also take advantage of reCAPTCHA Mailhide. In Dada Mail, this is used to protect individual email addresses in mailing list archives. Before an email address can be viewed, a CAPTCHA has to be solved. 

=head2 Configuration 

Mailhide can also be configued in the Dada Mail Installer. 

If not already shown, click the button, B<Show/Hide Advanced Options...>, then check the option, B<Configure CAPTCHA Options>. Additional CAPTCHA settings will then be revealed. 

Under, B<reCAPTCHA Mailhide Settings>, enter in your B<reCAPTCHA Mailhide Public Key> and B<reCAPTCHA Mailhide Private Key>, much like you did for your CAPTCHA settings, above. You may create those keys here: 

L<https://www.google.com/recaptcha/admin#mailhide/apikey>

=head2 Enabling

In your list control panel, go to: B<Manage Archives - Advanced Archive Options>, under, B<Email Address Protection> select, B<reCAPTCHA MailHide>.

=head2 Requirements

You may need to separately install the C<Captcha::reCAPTCHA::Mailhide> CPAN Perl module, in order to gain reCAPTCHA Mailhide support. 

=cut
