=pod

=head1 WYSIWYG Editors and File Browsers

Dada Mail supports the use of third party WYSIWYG HTML editors to allow you to compose and edit HTML mailing list messages. This allows you to send rich text messages, right in Dada Mail's list control panel, without needing to know any HTML. The HTML produced by these WYSIWYG editors is actually pretty good for the use of HTML emails, as most of the text formatting is done with inline css styles and these editors also have the ability to make simple HTML tables for basic layouts. 

=head1 Supported Editors 

Dada Mail supports the following WYSIWYG HTML editors: 

=over

=item * CKEditor

=item * FCKeditor

=item * Tiny MCE

=back

FCKeditor is only supported for backwards compatibility with previous versions of Dada Mail, and is not what we recommend that you us . We will be removing support for FCKeditor in a future version of Dada Mail. 

=head2 Supported File Browsers - KCFinder

As well as the core WYSIWYG functionality, Dada Mail also supports the B<KCFinder> File Browser, allowing you to browse a directory on the server itself, as well as upload new files. Images uploaded may then be inserted into your HTML messages. 

Dada Mail supports B<KCFinder> in all three WYSIWYG editors that it also supports. Dada Mail does I<not> ship with support for the B<CKFinder> file browser, which is developed by the same company that develops CKEditor, because it requires an additional commercial license. KCFinder is free software. 

Dada Mail also does not ship with FCKeditor's default file browser "connector", as it is difficult to set up correctly, buggy and has a reputation for being very insecure. 

=head1 Mailing List Configuration

For each of your mailing lists, only one WYSIWYG editor may be used at one time. You may configure which WYSIWYG editor to work with, or to use no WYSIWYG editor at all. 

=head1 Installing and Configurating

By far the easiest way to install and configure any of the WYSIWYG editors/file browser that Dada Mail supports is to use the included Dada Mail Installer. When using the installer, you will simply need to set the absolute path to a directory that you would like the editors to be installed under, as well as set the corresponding URL - the Dada Mail Installer will do the rest. A sane default should already be filled in for you. 


=head1 Manual Installation and Configuration

To install any of the editors/file browser, see their individual documentation. If you already have a prefered and working installation of any of these editors, it's also a simple task of just replacing what's potentially already set for the editor installation you already have. 

Configuration of the editors to work with Dada Mail is done in the configuration variable, C<$WYSIWYG_EDITOR_OPTIONS>, which looks like this: 

	$WYSIWYG_EDITOR_OPTIONS = { 
		fckeditor => { 
			enabled => 0, 
			url     => '', 
		}, 
		ckeditor    => { 
			enabled => 0, 
			url     => '', 
		}, 
		tiny_mce => { 
			enabled => 0, 
			url     => '', 
		},
	};

For each editor's paramaters (C<fckeditor>, C<ckeditor>, C<tiny_mce>), there are two more named paramaters, C<enabled> and, C<url>. 

C<enabled> can be set to C<1> to enable the editor, or C<0> to disable. Disabled editors will not be available to be used in your mailing lists, even if they're installed on your hosting account. If any of your mailing lists have selected a editor that you then disable, they will default in using B<no> editor. 

C<url> should hold the base URL for the editor itself - make sure to have a full URL, starting with, "C<http://>"

Configuration for the KCFinder file browser to work with Dada Mail is done in the C<$FILE_BROWSER_OPTIONS> variable, which should look like this: 

	$FILE_BROWSER_OPTIONS ||= { 
		kcfinder  => { 
			enabled      => 0, 
			url          => '', 
			upload_dir   => '', 
			upload_url   => '',
			session_name => 'PHPSESSID', 
			session_dir  => '/tmp',
		},
	};

The, C<kcfinder> paramater has additional paramaters to configure: 

C<enabled> can be set to C<1> to enable KCFinder, or C<0> to disable. 

C<url> should hold the base URL for KCfinder itself. 

C<upload_dir> should hold the absolute server path to the directory you would like files that are uploaded using KCFinder to be saved at. You will want this path to be under your C<public HTML> directory, so that you can access th

C<upload_url> should hold the corresponding URL to the C<upload_dir> variable - the  C<upload_dir> and C<upload_url> should map to each other. 

C<session_name> and C<session_dir> are used to configure and manage the sessioning information between Dada Mail and KCFinder. KCFinder will only work in Dada Mail, if the correct sessioning information is passed from Dada Mail, to KCFinder. For more information, please see KCFinder's docs on Integration and Sessioning: 

L<http://kcfinder.sunhater.com/docs/integrate>

The default values for C<session_name> and C<session_dir> should work for the majority of users. Additional configuration for all three supported editors will be required to get KCFinder working with Dada Mail and these editors, which is also explained on that page. There's potential that the values set in C<session_name> and C<session_dir> I<won't work for your environment>. We'd like to know about it and what does work for you. This doc does not go over what exactly needs to be configured in Dada Mail, as the best way to configure the WYSIWYG Editor/KCFinder/Dada Mail is still in flux. Best thing to do is to set up these editors and KCFinder with the Dada Mail Installer and study its configuration. We'd love your feedback.

=head2 Additional Configuration Files

CKEditor and Tiny MCE also expect an additional configuration file called, C<dada_mail_config.js> to be saved in the base URL of the editor. These configuration file should hold any additional configuration you would like for Dada Mail specifically. Setting up these editors to work with KCFinder is not covered in the configuration examples below. 

Below are bare-bone examples of what these configuration files should hold: 

=head3 Tiny MCE

	tinyMCE.init({
			theme : "advanced",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			mode : "specific_textareas",
			editor_selector : "html_message_body"
			
	});

=head3 CKEditor

There is nothing specific that the CKEditor needs in its C<dada_mail_config.js>. You can start by copying the C<config.js> file to a file called, C<dada_mail_config.js> and make any additional changes that you would like in that file. 

=head3 FCKeditor

Similar to CKEditor, there is nothing specific that the FCKeditor needs in its C<dada_mail_config.js>. You can start by copying the C<fckconfig.js> file to a file called, C<dada_mail_config.js> and make any additional changes that you would like in that file. 

=head2 KCFinder

KCFinder does not require this additional JavaScript file, but it's own default configuration file, C<kcfinder/config.php> will be edited by the Dada Mail Installer. 

When looking over this config file, One thing of particular importance is a variable B<not> changed by Dada Mail, which look like this: 

	$_CONFIG = array(
	
	    'disabled' => true,

Setting the, C<disabled> variable to, C<false> (it's confusing, we know!) will circumvent the security of the KCFinder that's afforded by the sessioning system and leave your account open to unauthorized file uploads and potential exploits. So don't do that! 

=head2 Image Drag and Drop Support

When using a supported browser, Dada Mail supports dragging and dropping  images into the HTML WYSIWYG editor. 

Image data is embedded in the HTML source of the message you write. Dada Mail will convert this embedded data into a file that will be saved in the KCFinder  image/file upload directory. The image will then be available  by browsing your upload directory, using the file browser/uploader itself. 



=cut