=pod

=head1 Installing and Configuring Dada Mail

=head1 Step #1: Download Dada Mail

Here's the direct download to Dada Mail v4.7.0 alpha 1: 

L<https://github.com/downloads/justingit/dada-mail/dada-4_7_0-alpha1.tar.gz>

=head2 Pro Dada Subscriber?

Download Pro Dada at: 

L<http://dadamailproject.com/pro_dada>

=head1 Step #2 Upload the, "dada-4_7_0-alpha1.tar.gz" distro to your cgi-bin

Download the C<dada-4_7_0-alpha1.tar.gz> distro (you will B<not> have to uncompress the distribution) and then upload it to your hosting account's I<cgi-bin>.

I<In these directions we suggest the cgi-bin, but feel free to use any directory that you B<know> will work.>

=head1 Step #3 Upload the, "uncompress_dada.cgi" script to your cgi-bin

Download the, C<uncompress_dada.cgi> script from here: 

=for html <ul><li><strong><a href="https://github.com/justingit/dada-mail/raw/v4_7_0-alpha1_stable-2011_08_26/uncompress_dada.cgi">uncompress_dada.cgi</a> (Save Page/Link As...)</strong></li></ul>

and upload this script (PlainTest/ASCII mode - NOT binary!) to your hosting account's I<cgi-bin> - right alongside the I<dada-4_7_0-alpha1.tar.gz> distro you just put up. 

=head1 Step #4 Change permissions of the, "uncompress_dada.cgi" file to, "755"

=head1 Step #5 Visit the, "uncompress_dada.cgi" script in your web browser. 

The, C<uncompress_dada.cgi> should attempt to uncompress the I<dada-4_7_0-alpha1.tar.gz> distro, change the necessary permissions of various files and prep the actual installer for you to use. 

Once it's finished running, you should be presented a link to use the actual installer. Click the link at the end of the screen and go ahead and configure Dada Mail! 

=head1 Configuring Dada Mail with the, "install.cgi" Script 

The installer should be relatively straightforward on how it's used - just fill it out with the information it's asking for. Below, we'll explain exactly what it's looking for. 

=head2 A Warning Up Top? 

It's possible that before you even start using Dada Mail, that you'll receive a warning stating that Dada Mail won't be able to edit the, C<dada/DADA/Config.pm> file. This would be because there's a difference in file permissions/privileges between the user that the installer is running under and the user that owns the C<dada/DADA/Config.pm> file. 

This means you'll need to edit I<one> line in the C<dada/DADA/Config.pm> file to get Dada Mail running correctly.

=head2 ".dada_files " Directory Location

The first thing you'll need to fill out in the installer is the location to place the, C<.dada_files> directory. 

The installer will do its best to pre-fill out the best location for you - and you can just use it's best guess and forgo having to know the exact details. 

For most installations, we suggest having the installer create the, C<.dada_files> directory in your B<home directory>. All you'll need to do is fill out where your home directory is located. Find out what the location of your home directory is from your webhost, if you do not already know it. 

=over

=item * Select B<AUTO> 

If the installer has successfully selected your home directory, or you like the directory it has selected. 

=item * Select B<MANUAL> 

I<(and fill in the location you'd like)> if the installer doesn't pick a good location or you'd rather the directory be somewhere else. 

=back

=head2 Dada Mail URL

The Dada Mail URL is simply the URL that you will access Dada Mail's, C<mail.cgi> file from. This form field should be filled out automatically, but if something doesn't look right, just look at the URL of the installer - for example, if the URL of the installer is: 

L<http://example.com/cgi-bin/dada/installer/install.cgi>

Your B<Dada Mail URL> will be: 

L<http://example.com/cgi-bin/dada/mail.cgi>

=head2 Dada Mail Root Password

The, B<Dada Mail Root Password> is the main administrative password to your Dada Mail installation - choose a good, strong password - all you'll need to do is enter it twice, just to make sure you know exactly what it's set to. 

=head2 Dada Mail Backend

Dada Mail will need to save its mailing lists and other information in various files and/or an SQL database. The SQL database is optional, but we highly suggest using it:

=over

=item * upgrades are easier

=item * your information will be saved more securely

=item * any migrations you do will be easier, more and fancier features will be available for you

=back

Tons of stuff

=head4 Default 

Select B<Default> if you cannot, don't know how, or do not want the SQL backend option I<(we really suggest going the distance and using the SQL backend)>

=head4 MySQL or PostgreSQL

Both B<MySQL> and B<PostgreSQL> will have the same features available and work under the hood, basically the same way. We like PostgreSQL better, but MySQL is going to be tested a bit more thouroughly and probably is more familiar to most people, so at the moment, it's the backend that we recommend. 

When you select one of the SQL backends, you'll also be asked to fill in the SQL connection information, including the database server, the port number, the name of the database itself and the username and password. 

The database has to be set up beforehand. It's not too hard to do if you have a cPanel w/phpMyAdmin to help you along. Just note the B<Server>, B<Database>, B<Username> and B<Password>, once you create the database (No tables have to be created, beforehand). The SQL user will need full priviliges to your database. We don't suggest, for security reasons, giving this same user any permissions to any other database. 

=over

=item * Database Server

The majority of the time, you'll set this to, C<localhost>, unless you have specific instructions to set it to something a little different. 

=item * Database

Fill this out to whatever you've called your database.

=item * Port

By default, this is set to, C<auto>. If you do not know what port your database uses, Dada Mail will take its best guess. By default, if you use MySQL, the port will be, C<3306>, for PostgreSQL, the port will be: C<5432>. Unless your database is set up different from the default configuration, these two numbers should work for the majority of people out there. 

=item * Username

Fill this with the username that's associated with your database

=item * Password

Fill this with the password associated with the username.

=back

=head3 Another Shortcut to Upgrading

If you have an already existing database from a previous Dada Mail installation, you may fill in the SQL server login information for this existing database and Dada Mail will use it, instead of creating a set of new tables for you. This is particularily useful if you're B<moving> Dada Mail from one server to another. 


=head2 Plugins/Extensions

Optionally, you may also install many of the plugins and extensions that come with Dada Mail. Access to the plugins/extensions will be available in the list control panel's admin menu.

Some of the plugins/extensions have additional configuration that will need to done, before they work completely. For the majority of these plugins/extensions, you'll need to also set a cron job. 

One plugin, the bounce handler, also requires you to fill out the credentials for the bounce handler email account you need to set up to capture bounced emails. 

=head2 Completing the Installation and Configuration. 

Once you've filled out the form completely, just click the, B<Configure Dada Mail!> button. The screen will refresh and go about configuring Dada Mail for your hosting setup. 

If everything works well (and we hope it does) you should be all set to run Dada Mail.

=head2 Do You Need to Manually Edit The, "dada/DADA/Config.pm" File? 

There's a possibility, especially if you were issued the warning before filling out the configuration form, that you'll have to edit a line in the, C<dada/DADA/Config.pm> file. If this is the case, the installer will show you which file to look for and what to change it to. 

Be careful when editing this file, as any error will stop Dada Mail from working. When saving the file and putting it back up to your hosting account, make sure to upload the file in ASCII/Plain Text mode, NOT binary! 

=head2 Moving the, "installer" directory

Dada Mail will not start working, until you move the, C<dada/installer> directory out of the way. This is a security precaution, so someone else doesn't come along and attempt to reconfigure your Dada Mail! 

The provided button should do the trick, but if it fails (it'll let you know), you'll have to remove it manually. If you had to do the above step manually, you'll most likely have to do this step manually, too. 

=head2 Making Additional Edits

The installer should give you the full path to the, C<.dada_config> file it creates. This is the file that is written that holds your configuration that the installer just created. There's a ton of additional configuration options you can set - the installer just gets you up and running correctly. 

Making additional configurations is a lot more advanced than running the installer, so be careful when editing this file - make a backup, first. 

=head2 Running Dada Mail for the First Time

Once you've gotten the, C<dada/DADA/Config.pm> file edited (if needed) and moved the, C<installer> directory out of the way, it's time to begin using Dada Mail. Click the, C<Start Working With Dada Mail!> button to begin!

Good Luck! 

=head1 Command Line Interface

An alternative, command line interface is available, instructions can be 
found on how to use it, by invoking the script with the, C<--help> flag, 

 shell>./installer.cgi --help

most of the options available on the web-based interface are available in the command line interface, except the installation of the plugins/extensions. 

=head1 Screencasts

The below screencasts go through the installation process: 

B<How to Download, Install and Configure Dada Mail v4.7.0 alpha 1>

=for html <p><iframe width="853" height="510" src="http://www.youtube.com/embed/MWz8O13yc0s?hd=1" frameborder="0" allowfullscreen></iframe></p>

=head2 Manual Installation

We suggest using the Dada Mail Installer, but you can still install Dada Mail manually: 

L<http://dadamailproject.com/support/documentation/manually_install_dada_mail.pod.html>

=cut

