
=pod

=head1 Installing and Configuring Dada Mail

=head2 Manual Installation

We suggest using the Dada Mail Installer, but you can still install Dada Mail manually: 

L<http://dadamailproject.com/support/documentation/manually_install_dada_mail.pod.html>

=head1 Step #1: Download Dada Mail

Here's the direct download to Dada Mail v4.3.0: 

L<https://github.com/downloads/justingit/dada-mail/dada-4_3_0.tar.gz>


(If you have Pro Dada, you can download v4.3.0 of Pro Dada here:)

L<http://dadamailproject.com/pro_dada/index.cgi?rm=download_file&filename=pro_dada-4_3_0.tar.gz>

Save the distribution to your Desktop Computer (you will B<not> have to uncompress the distribution) and then upload the, tar.gz file to your hosting account's I<cgi-bin>. 

=head1 Step #2 Upload the, "uncompress_dada.cgi" script to your cgi-bin

Download the, C<uncompress_dada.cgi> script from here: 

CHANGE
=for html <ul><li><strong><a href="https://github.com/justingit/dada-mail/raw/v4_3_0-beta1-2010_11_16/uncompress_dada.cgi">uncompress_dada.cgi</a> (Save Page/Link As...)</strong></li></ul>

and upload this script (PlainTest/ASCII mode - NOT binary!) to your hosting account's I<cgi-bin> - right alongside the tar.gz file you just put up. 

=over

=item * Change permissions of the, C<uncompress_dada.cgi> file to, B<755>

=item * Visit the, C<uncompress_dada.cgi> script in your web browser. 

=back

The, C<uncompress_dada.cgi> should attempt to uncompress the tar.gz distro, change the necessary permissions of various files and prep the actual installer for you to use. 

Once it's finished running, you should be presented a link to use the actual installer. Click the link at the end of the screen and go ahead and configure Dada Mail! 

I<(If you do not see this link, or the script wasn't able to do its job, you may have to go on to Step #3:)>

=head2 Step #3 - Only If Step #2 Doesn't Work Automatically 

(Or, if you'd rather do this part of the installation manually:)

=head3 Uncompress the Distribution

The tar.gz distribution you just downloaded to your Desktop Computer should uncompress to one folder/directory called, B<dada>.

=head3 Upload the, "dada" directory into your cgi-bin

There are a lot of files and this will take a few minutes.

I<(If you're familiar with accessing your hosting account via ssh, feel free to simply upload the distribution to your hosting account and uncompress from there.)>

=head3 Change the name of the, "dada/installer-disabled" directory to, "dada/installer"

By default, the installer is disabled, so not to pose as a security issue. Rename the, I<dada/B<installer-disabled>> directory to, I<dada/B<installer>>. 

=head3 Change permissions of the, "dada/mail.cgi" and "dada/installer/install.cgi" scripts to, "755"

B<BOTH> of these scripts need to have their permissions changed to, B<755>

=head3 Visit the, dada/installer/install.cgi script in your web browser

The, C<install.cgi> script should take over from there. 

=head1 Configuring Dada Mail with the, "install.cgi" Script 

The installer should be relatively straightforward on how it's used - just fill it out with the information it's asking for. Below, we'll explain exactly what it's looking for. 

=head2 A Warning Up Top? 

It's possible, before you even start using Dada Mail, that you'll receive a warning stating that Dada Mail won't be able to edit the, C<dada/DADA/Config.pm> file. This would be because there's a difference in file permissions/privileges between the user that the installer is running under,and the user that owns the C<dada/DADA/Config.pm> file. 

This will mean, if you're comfortable with the idea, you'll need to edit I<one> line in the C<dada/DADA/Config.pm> file, to get Dada Mail running correctly. The majority of the time, this won't be the case and if you're selecting B<AUTO> for the first step, it will not be the case, even if there is the warning. 

=head2 ".dada_files " Directory Location

The first thing you'll need to fill out in the installer is the location to place the, C<.dada_files> directory. 

This will be the hardest for a casual user of Dada Mail to know what to correctly fill out. 

Luckily, the installer will do its best to pre-fill out the best location for you - and you can just use it's best guess and forgo having to know the exact details. 

For most installations, we suggest having the installer create the, C<.dada_files> directory in your home directory. All you'll need to do is fill out where your home directory is located. This location should be something you can find out from your webhost, if you don't know it yourself. 

=over

=item * Select B<AUTO> 

If you do not know where your home directory is, or if you like the location that the installer finds. 

=item * Select B<MANUAL> 

(and fill in the location you'd like) if the installer doesn't pick a good location or you'd rather the directory be somewhere else. 

=back

=head3 Upgrading? 

If you are upgrading Dada Mail, you may type in the current location of your, C<.dada_files> directory. 

Make sure to double check the Dada Mail changelogs and fix any incompatibility between versions. Currently, this will be something you'll have to do manually.

If the installer finds your current C<.dada_files> directory, it'll give you a new option, labeled,  I<I know that the, ".dada_files" directory already exists >. Check this option - all other options will then be hidden. 

=head2 Dada Mail URL

The Dada Mail URL is simply the URL that you will access Dada Mail's, C<mail.cgi> file from. This form field should be filled out automatically, but if something doesn't look right, just look at the URL of the installer - for example, if the URL of the installer is: 

L<http://example.com/cgi-bin/dada/installer/install.cgi>

Your B<Dada Mail URL> will be: 

L<http://example.com/cgi-bin/dada/mail.cgi>

=head2 Dada Mail Root Password

The, B<Dada Mail Root Password> is the main administrative password to your Dada Mail installation - choose a good, strong password - all you'll need to do is enter it twice, just to make sure you know exactly what it's set to. 

=head2 Dada Mail Backend

Dada Mail will need to save its mailing lists and other information in various files and/or an SQL database. The SQL database is optional, but we B<I<really, really, really>> suggest using it - upgrades are easier, your information will be saved more securely, any migrations you do will be easier, more and fancier features will be available for you - a ton of stuff. 

=over

=item * Select, Default 

If you cannot, don't know how, or don't want the SQL backend option (we really suggest going the distance and using the SQL backend) 

=item * Select, MySQL or PostgreSQL for the SQL backend

Both MySQL and PostgreSQL will have the same features available and work under the hood, basically the same way. We like PostgreSQL better, but MySQL is going to be tested a bit more thouroughly and probably is more familiar to most people, so at the moment, it's the backend that we recommend. 

=back

When you select one of the SQL backends, you'll also be asked to fill in the SQL connection stuff, including the database server, the port number, the name of the database itself and the username and password. 

The database has to be set up beforehand. It's not too hard to do if you have a cPanel w/phpMyAdmin to help you along. Just note the Server, Database, Username and Password, once you create the database (No tables have to be created, beforehand). The user will need full priviliges to your database. We don't suggest, for security reasons, giving this same user any permissions to any other database. 

=over

=item * Database Server

The majority of the time, you'll set this to, C<localhost>, unless you have specific instructions to set it to something a little different. 

=item * Database

Fill this out to whatever your database is called. 

=item * Port

By default, this is set to, C<auto>. If you do not know what port your database uses, Dada Mail will take its best guess. By default, if you use MySQL, the port will be, C<3306>, for PostgreSQL, the port will be: C<5432>. Unless your database is set up different from the default configuration, these two numbers should work for the majority of people out there. 

=item * Username

Fill this with the username that's associated with your database

=item * Password

Fill this with the password associated with the username.

=back

=head3 Another Shortcut to Upgrading

If you have an already existing database from a previous Dada Mail installation, you may fill in the SQL server login information for this existing database and Dada Mail will use it, instead of creating a set of new tables for you. 

=head2 Completing the Installation and Configuration. 

Once you've filled out the form completely, just click the, C<Configure Dada Mail!> button. The screen will refresh and go about configuring Dada Mail for your hosting setup. 

If everything works well (and we hope it does) you should be all set to run Dada Mail.

=head2 Do You Need to Manually Edit The, "dada/DADA/Config.pm" File? 

There's a possibility, especially if you were issued the warning before filling out the configuration form, that you'll have to edit a line in the, C<dada/DADA/Config.pm> file. If this is the case, the installer will show you which file to look for and what to change it to. 

Be careful when editing this file, as any error will stop Dada Mail from working. When saving the file and putting it back up to your hosting account, make sure to upload the file in ASCII/Plain Text mode, NOT binary! 

=head2 Moving the, "installer" directory

Dada Mail will not start working, until you move the, C<dada/installer> directory out of the way. This is a security precaution, so someone else doesn't come along and attempt to reconfigure your Dada Mail! 

The provided button should do the trick, but if it fails (it'll let you know), you'll have to remove it manually. If you had to do the above step manually, you'll most likely have to do this step manually, too. 

=head2 Making Additional Edits

The installer should give you the full path to the, C<.dada_config> file it creates. This is the file that is written that holds your configuration that the installer just created. There's a ton of additional configuration options you can set - the installer just gets you up and running correctly. 

Making additional configurations is a lot more advanced than running the installer, so be careful when editing this file - make a backup, first. 

=head2 Running Dada Mail for the First Time

Once you've gotten the, C<dada/DADA/Config.pm> file edited (if needed) and moved the, C<installer> directory out of the way, it's time to begin using Dada Mail. Click the, C<Start Working With Dada Mail!> button to begin!

Good Luck! 

=head1 Screencasts

The below screencasts go through the installation process: 

B<How to Download, Install and Configure Dada Mail v4.2.0>

=for html <p><object width="960" height="745"><param name="movie" value="http://www.youtube.com/v/md8NNRkjRR4?fs=1&amp;hl=en_US&amp;hd=1&amp;color1=0x2b405b&amp;color2=0x6b8ab6"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/md8NNRkjRR4?fs=1&amp;hl=en_US&amp;hd=1&amp;color1=0x2b405b&amp;color2=0x6b8ab6" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="960" height="745"></embed></object></p>

B<Install and Configure Dada Mail 4.2.1 w/the MySQL Backend>

=for html <p><object width="960" height="745"><param name="movie" value="http://www.youtube.com/v/A_YRRlmIxak?fs=1&amp;hl=en_US&amp;hd=1&amp;color1=0x2b405b&amp;color2=0x6b8ab6"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/A_YRRlmIxak?fs=1&amp;hl=en_US&amp;hd=1&amp;color1=0x2b405b&amp;color2=0x6b8ab6" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="960" height="745"></embed></object></p>


=cut

