=pod

=head1 Dada Mail Installation

Please see the below docs for information on how to install Dada Mail: 

=head2 Installation Overview

http://dadamailproject.com/installation

=head2 Install Dada Mail using the Dada Mail Installer: 

L<./features-dada_mail_installer.pod.html>

=head2 Manual Installation

http://dadamailproject.com/installation/installation_advanced.html

=head2 How to Upgrade Dada Mail

L<http://dadamailproject.com/support/documentation/FAQ-basic_2_contemporary_installation.pod.html>

=cut
