=pod

=head1 Installing and Configuring Dada Mail

=head2 Step #1: Download Dada Mail

=begin html 

<uL>
<p>
    <li>
    <a href="https://sourceforge.net/projects/dadamail/files/dada-8_0_2.tar.gz/download">
        Click here to download to Dada Mail
    </a> 
    </li>
    <li>
    Or, if you're a Pro Dada Subscriber, 
    <a href="http://dadamailproject.com/pro_dada">
        click here to download to Pro Dada
    </a>
    </li>
</ul>
</p>
    
    <p><a href="http://dadamailproject.com/purchase/pro.html">
    Here's more information about Pro Dada
    </a>
    </p>
    
</p>

=end html 

I<When installing Pro Dada, use, B<pro_dada-8_0_2.tar.gz> as the name of the distribution, in these directions.>


=head2 Step #2 Upload the, "dada-8_0_2.tar.gz" distro into your cgi-bin

Once you downloaded the C<dada-8_0_2.tar.gz> distro, upload it to your hosting account's I<cgi-bin>.

=begin html

<div class="see_also">
<p>
 In these directions, we suggest uploading into the <code>cgi-bin</code> directory, but feel free to use any directory that you <strong>know</strong> will work. See also: <a href="./FAQ-install_upgrade.pod.html#installing_dada_mail_in_a_directory_other_than_in_your__cgi_bin">Installing Dada Mail in a directory other than in your, &quot;cgi-bin&quot;</a>
</p>
</div>

=end html

=head2 Step #3 Upload the, "uncompress_dada.cgi" script into your cgi-bin

Download the, C<uncompress_dada.cgi> script from here: 

=begin html 

<ul>
<li><strong><a href="https://raw.github.com/justingit/dada-mail/v8_0_2-stable_2015_04_24/uncompress_dada.cgi">uncompress_dada.cgi</a> (Save Page/Link As...)</strong></li></ul>

=end html

and upload this script (PlainTest/ASCII mode - NOT binary!) to your hosting account's I<cgi-bin> directory - right alongside the I<dada-8_0_2.tar.gz> distro you just put up. 

=head2 Step #4 Change permissions of the, "uncompress_dada.cgi" file to, "755"

=head2 Step #5 Visit the, "uncompress_dada.cgi" script in your web browser. 

The, C<uncompress_dada.cgi> should attempt to uncompress the I<dada-8_0_2.tar.gz> distro, change the necessary permissions of various files and prep the actual installer for you to use. 

Once it's finished running, you should be presented with a link to use the actual installer. Click the link at the bottom of the screen and go ahead and configure Dada Mail! 

=begin html

<div class="see_also">

<p>See, <a href="./FAQ-install_upgrade.pod.html#prepping_dada_mail_manually">Prepping Dada Mail Manually</a> if this doesn't happen and you get a message in your browser window, sort of like this: </p>

<pre>
Can't find dada-8_0_2.tar to uncompress!

You may have to uncompress and prep Dada Mail manually.
</pre> 

</div>

=end html

=head2 Configuring Dada Mail with the Dada Mail Installer

The installer should be relatively straightforward on how it's used - just fill it out with the information it's asking for. Below, we'll walk through all the options: 

=head2 Choose, "Installation"

The first screen of the installer will ask you if you'd like to Install, or Upgrade Dada Mail. Choose, B<Install> and click, B<Continue>

=head2 A Warning Up Top? 

It's possible that before you even start using the Dada Mail installer, that you'll receive a warning stating that Dada Mail won't be able to edit the, C<dada/DADA/Config.pm> file. This would be because there's a difference in file permissions/privileges between the user that the installer is running under and the user that owns the C<dada/DADA/Config.pm> file. 

This means you'll need to edit I<one> line in the C<dada/DADA/Config.pm> file to get Dada Mail running correctly.

=head2 ".dada_files " Directory Location

Fill out the location on where to place the, C<.dada_files> directory. 

For most installations, we suggest having the installer create the, C<.dada_files> directory in your B<home directory>. All you'll need to do is fill out where your home directory is located. Find out what the location of your home directory is from your webhost, if you do not already know it. 

The installer will do its best to pre-fill out its best guess for a good location for you.

=over

=item * Select B<AUTO> 

If the installer has successfully selected your home directory, or you like the directory it has selected. 

=item * Select B<MANUAL> 

I<(and fill in the location you'd like)> if the installer doesn't pick a good location or, you'd rather the directory be somewhere else. 

=begin html

<div class="see_also">
<p>
	See, <a href="./FAQ-install_upgrade.pod.html#_dada_files_directory_location">.dada_files Directory Location</a> for help on picking an alternative location for your .dada_files directory.
</p>
</div> 

=end html

=back

=head2 Dada Mail URL

The Dada Mail URL is simply the URL that you will access Dada Mail's, C<mail.cgi> file from. This form field should be filled out automatically, but if something doesn't look right, just look at the URL of the installer - for example, if the URL of the installer is: 

L<http://example.com/cgi-bin/dada/installer/install.cgi>

Your B<Dada Mail URL> will be: 

L<http://example.com/cgi-bin/dada/mail.cgi>

=head2 Support Files Directory

Dada Mail needs a collection of static files (image files, css files, javascript files, etc) to work correctly. During configuraation, the Installer will copy over these resources to a new directory on your hosting account called, B<dada_mail_support_files>. You will need to tell the Installer where this new directory should reside. 

Unlike the C<.dada_files> directory, you will want to be able to access the B<dada_mail_support_files> directory through your web browser.

By default, a I<pretty good guess> is made for the location to set both the Server Absolute Path to your base Public HTML directory, as well as the corresponding URL to access that same directory through your web browser. 

If the default location looks fine, keep it as-is. If you'd like to customize/fix where this directory should live, you may do so. 

The Installer will create the, C<dada_mail_support_files> under the directory you set, as well as copy over a few directories holding the required resources. 

B<Make sure> That this URL and the Program URL either B<both> domain name, or are located on the same subdomain. The following examples will work great: 

=over

=item Same Domain

B<Program URL>: I<http://B<>example.com/cgi-bin/dada/mail.cgi>

B<Dada Mail Support Files Dir:>  I<http://B<>example.com/dada_mail_support_files>

=item Same Subdomain

B<Program URL>: I<http://B<www.>example.com/cgi-bin/dada/mail.cgi>

B<Dada Mail Support Files Dir:> I<http://B<www.>example.com/dada_mail_support_files>

=item Same Subdomain

B<Program URL>: I<http://B<list.>example.com/cgi-bin/dada/mail.cgi>

B<Dada Mail Support Files Dir:> I<http://B<list.>example.com/dada_mail_support_files>

=back 

The following examples will B<not> work well: 

=over

=item Different Subdomain!

B<Program URL>: I<http://B<www.>example.com/cgi-bin/dada/mail.cgi>

B<Dada Mail Support Files Dir:> I<http://B<>example.com/dada_mail_support_files>

=item Different Subdomain!

B<Program URL>: I<http://B<>example.com/cgi-bin/dada/mail.cgi>

B<Dada Mail Support Files Dir:> I<http://B<list.>example.com/dada_mail_support_files>

=back

=head2 Dada Mail Root Password

The, B<Dada Mail Root Password> is the main administrative password to your Dada Mail installation - choose a good, strong password - all you'll need to do is enter it twice, just to make sure you know exactly what it's set to. This password will be stored in a one-way encrypted form, so there will be no way to retrieve it, later on. 

=head2 Dada Mail Backend

Dada Mail will need to save its mailing lists and other information inan SQL database.

=head3 Choices: MySQL, PostgreSQL or SQLite

Both B<MySQL> and B<PostgreSQL> will have the same features available and work under the hood, basically the same way. We recommend either equally.

B<SQLite> is also an option, but we recommend using it only for local testing purposes. 

When you select one of the SQL backends, you'll also be asked to fill in the SQL connection information, including the database server, the port number, the name of the database itself and the username and password. 

This database has to be set up beforehand. It's not too hard to do if you are running an account under cPanel w/phpMyAdmin to help you along. Just note the B<Server>, B<Database>, B<Username> and B<Password>, once you create the database (You will not need to create any tables beforehand). The SQL user will need full priviliges to your database. For security reasons, we don't suggest giving this same user any permissions to any other database. 

=over

=item * Database Server

The majority of the time, you'll set this to, C<localhost>, unless you have specific instructions to set it to something a little different. 

=item * Database

Fill this out to whatever you've called your database.

=item * Port

By default, this is set to, C<auto>. If you do not know what port your database uses, Dada Mail will take its best guess. By default, if you use MySQL, the port will be, C<3306>, for PostgreSQL, the port will be: C<5432>. Unless your database is set up different from the default configuration, these two numbers should work for the majority of people out there. 

=item * Username

Fill this with the username that's associated with your database

=item * Password

Fill this with the password associated with the username.

=back

=head4 Test Your SQL Connection

A button labeled, B<Test Your SQL Connection> when pressed, will run a quick connection test, to see if Dada Mail can connect to your SQL server. This can help you make sure your SQL credentials for Dada Mail are working correctly. 


=head2 Plugins/Extensions

Optionally, you may also install many of the plugins and extensions that come with Dada Mail. Access to the plugins/extensions will be available in the list control panel's left hand admin menu, under, B<Plugins>

Some of the plugins/extensions have additional configuration that will need to done, before they work completely.

One plugin, B<Bounce Handler>, also requires you to fill out the credentials for the Bounce Handler email account you need to set up to capture bounced emails. See the documentation on the Bounce Handler for more information: 

L<http://dadamailproject.com/d/bounce_handler.html>

=head2 WYSIWYG Editors

Optionally, you may also configure the B<WYSIWYG> editors that come bundled with the Dada Mail distribution. These WYSIWYG editors will enable you to author and edit your HTML Mailing List Messages right in your List Control Panel. 

=head3 Install and Configure WYSIWYG Editors 

If you would like to use the bundled WYSIWYG editors with Dada Mail, check the option, B<Install and Configure WYSIWYG Editors> - which is checked by default. Uncheck this option, if you'd like to skip setting up the WYSIWYG editors - the various options will be hidden. 

=head2 Advanced Configuration (Optional)

=begin html 

<p>Dada Mail's Installer also supports setting quite a few advanced global configuration settings and parameters. <a href="./install_dada_mail-advanced_configuration.pod.html">This section is covered in detail, here.
</a></p>

=end html

Many of the Advanced Configuration parameters are only available in Pro Dada: 

L<http://dadamailproject.com/purchase/pro.html> 

One notable exception is B<Amazon SES support>. 

=head2 Completing the Installation and Configuration. 

Once you've filled out the form completely, just click the, B<Configure Dada Mail!> button. The screen will refresh and go about configuring Dada Mail for you.

If everything works well (and we hope it does) you should be all set to run Dada Mail.

=head2 Setup the Scheduled Job (cronjobs)

For many things in Dada Mail, including making sure your mass mailings are going out correctly, B<you will need to set up the scheduled job>.

The unique command needed to run the required jobs will be shown. More information on the scheduled job: 

L<http://dadamailproject.com/d/features-scheduled_cronjobs.pod.html>

=head2 Moving the, "installer" directory

Dada Mail will not start working, until you move the, C<dada/installer> directory out of the way. This is a security precaution, so someone else doesn't come along and attempt to reconfigure your Dada Mail! 

The provided button, B<Move the, 'dada/installer' Directory, Disable the, 'install.cgi' script> should do the trick, but if it fails (it'll let you know), you'll have to remove it manually. If you had to do the above step manually, you'll most likely have to do this step manually, too. 

=head2 Do You Need to Manually Edit The, "dada/DADA/Config.pm" File? 

There's a possibility, especially if you were issued the warning before filling out the configuration form, that you'll have to edit a line in the, C<dada/DADA/Config.pm> file. If this is the case, the installer will show you which file to look for and what to change it to. 

Be careful when editing this file, as any error will stop Dada Mail from working. When saving the file and putting it back up to your hosting account, make sure to upload the file in ASCII/Plain Text mode, NOT binary! 


=head2 Making Additional Edits

The installer should give you the full path to the, C<.dada_config> file it creates. This is the file that is written that holds your configuration that the installer just created. There's a ton of additional configuration options you can set - the installer just gets you up and running correctly. 

Making additional configurations is a lot more advanced than running the installer, so be careful when editing this file - make a backup, first. How to configure more of Dada Mail's more advanced global features is covered here: 

L<http://dadamailproject.com/d/global_variables.pod.html>

=head2 Running Dada Mail for the First Time

Once you've gotten the, C<dada/DADA/Config.pm> file edited (if needed) and moved the, C<installer> directory out of the way, it's time to begin using Dada Mail. Click the, C<Start Working With Dada Mail!> button to begin!

Good Luck! 

=head2 Making Additional Global Configuration Changes using the Dada Mail Installer

Along with Installing Dada Mail, the Dada Mail Installer can also help reconfigure the global configuration of Dada Mail, at any time in the future, after your installation. 

Dada Mail comes with a plugin called, B<Global Configuration> to make this easy. It itself can be installed using the Dada Mail installer. Once installed, it can be accessed in the List Control Panel, under, "Plugins". Make sure you have logged into a mailing list, with the Dada Mail Root Pass, as it's not available, if you log in with the List Password. 

You can also re-enable the Dada Mail Installer Manually. 

To do this, you will need to: 

=over

=item * Rename the, "dada/installer-a.bunch.of.letters.and.numbers" directory back to, "dada/installer"

=item * Change the file permission of the, "dada/installer/install.cgi" script back to, "755" 

=item * Visit the "install.cgi" script in your browser

=back

When asked if you want to B<Install> or, B<Upgrade> your Dada Mail, choose, B<Upgrade> and make sure the textbox labeled, B<Current .dada_files Location> is filled in with the correct absolute path to the parent directory that holdsd your C<.dada_files> directory. Click the button labeled, B<Continue...>, to bring you back to the Configuration screen. Make your changes on this screen (make sure to select, B<Create a new .dada_config file> on the top of the form). 

Once you've completed your configuration changes, click the B<Configure Dada Mail!> button as before, and follow the same directions you did during the installation, for the next screen. 

=head2 Screencast

This screencast goes step by step, slowly through the entire process of installing Dada Mail, on your own website: 

L<https://www.youtube.com/watch?v=x7PRauNDKA4> 

=head2 Command Line Interface

An alternative command line interface is available:

L<http://dadamailproject.com/d/install_dada_mail_cl.pod.html>

=cut

