=pod

=head1 REQUIREMENTS

Requirements needed to run Dada Mail

Dada Mail is designed to be fairly flexible in the type of environment you run it in, so long as that environment is Unix/Linux-like, you have access to Perl v5.10.1 or later, and your web server can execute CGI scripts. 

=head2 Environment

For the most part, Dada Mail is a web application; you interact with it via a web browser and it lives on top of a web server. 

Dada Mail can be run is a simple CGI app, a FastCGI app, or as a PSGI app.

Dada Mail is not a desktop application. 

When we talk about what operating system, version of Perl, etc that's needed for Dada Mail to run - we're talking about what's needed on the I<server> end. All you need to use Dada Mail is a modern web browser (we suggest Firefox)  and because of this, any operating system that can run a modern web browser can be used.

=head2 Supported Operating Systems

Linux, Free BSD and Mac OS X should all work well. 

Solaris should also work well, but there are some issue with Sun's file locking system and Dada Mail. There may be workarounds.

Dada Mail isn't ever tested on a Windows Server or even Apache running on top of Windows. 

=head2 Perl 5.10.1

Sometimes, the default system Perl is a lower version that v5.10.1, but a more up-to-date version of Perl may be available at a different location than the what Dada Mail is set to, by default (C</usr/bin/perl>). More information: 

L<http://dadamailproject.com/d/FAQ-errors.pod.html#Perl-Version>

Since Dada Mail is a CGI app, you'll need support for Perl CGI scripts within your web server environment. 

Dada Mail is not a PHP script, so the version of PHP that you have available will not make much of a difference. 

=head2 Mail Transport Agent

Dada Mail can pass messages to send to a sendmail-like command that applications like sendmail, qmail, postfix, exim, etc come with, or it can pass messages using the SMTP protocol. Amazon SES support is also available. You will need one of these. Dada Mail is not an SMTP server itself. 

=head2 Backend Options

=head2 SQL Backend

Dada Mail is tested with MySQL B<5.7>, PostgreSQL B<8> and SQLite B<3>. We highly suggest using Dada Mail with either MySQL or PostgreSQL, and utilizing the latest versions of either. 

To utilize these backends, not only will you have to have these databases installed, you will need the Perl driver for these databases: 

=over

=item * MySQL 

C<DBD::mysql>

L<https://metacpan.org/pod/DBD::mysql>

=item * PostgreSQL

C<DBD::Pg>

L<https://metacpan.org/pod/DBD::Pg>

=item * SQLite

C<DBD::SQLite>

L<https://metacpan.org/pod/DBD::SQLite>

(only utilize the SQLite backend for testing purposes, and not for production)

=back

If these modules are not available, you'll need to install them using the operating system package management system, or using the C<cpan> or C<cpanm> command line tool, which should be installed when Perl is installed, or some hosts (like cPanel) may have a way to install Perl modules through cPanel. See: 

L<http://dadamailproject.com/d/FAQ-installing_CPAN_Perl_modules.pod.html>

=head2 LWP CPAN Perl Module

Dada Mail requires the C<LWP> CPAN Perl Module, which needs to be installed separately, if it's not already available. 

=head2 Configuration

Dada Mail is shipped with an installer. It can also upgrade your Dada Mail. 

=head2 Guide to Hosting Companies

This: 

L<http://dadamailproject.com/support/hosting.html>

is a very B<incomplete> list of hosting companies that seem to work well with Dada Mail. 

=cut
