=pod

=head1 Upgrade Dada Mail from a Mojo Marketplace/Simple Scripts Installation

=head2 Before Going Forward: 

Simple Scripts/Mojo Marketplace (henceforth, only reffered to as, "B<Mojo Marketplace>") is a great way to get started with Dada Mail, as their easy installer  makes it painless to begin using Dada Mail. 

Many people who start with a Mojo Marketplace installation of Dada Mail will then want to upgrade to Pro Dada, which allows them to manage more than three lists, and 1,000 subscribers, per mailing list. Below is the instructions on how to do so. Pro Dada can be purchased here: 

L<https://dadamailproject.com/purchase/pro.html>

Mojo Marketplace has, in its history of offering Dada Mail, sometimes changed the method that they install Dada Mail. Since starting to offer Dada Mail, their installs  are less and less different from the install directions we give, and thus, it's much easier to upgrade. 

These docs were written on 7/12/13, and go over installing v6.4.1 of Dada Mail, and upgrading to v6.5.0 of Pro Dada. 

=head2 Installing Dada Mail on the Mojo Marketplace. 

Before we upgrade, we're going to quickly go over how we've installed Dada Mail, using Mojo Marketplace. This demo is on a cPanel-based hosting account on Bluehost. 

Please feel free to skip this section, if you're familiar with how Mojo Marketplace installs Dada Mail. 

First, find the B<Simple Scripts> button in your cPanel, 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/search_for_simple_scripts.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

Click the, B<Simple Scripts/Mojo Marketplace> button to enter the Mojo Marketplace. This should open a new window/tab in your browser.

On the menu at the top, click on the link entitled, B<Scripts & Platforms>,  

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/find_scripts_and_platforms.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

When the page has refreshed, click on, B<Dada Mail> (it's under Mailing Lists). 


=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/find_dada_mail.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

That'll popup the modal menu to configure Dada Mail for your account. 

Click the button labeled, B<Start>,

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/start_install.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html


and when the modal window refreshes, pick a directory to install Dada Mail under. B<Thankfully> this installer will install the full, B<dada> directory under whatever you pick, which makes upgrading to your own install B<way easy>. 

I'm going to use the directory, B<mojomarketplace> as my own directory, just to make things obvious. Once you've enter in the directory to use, click the button labeled, B<Check Domain>.

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/check_domain.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

If everything checks out, B<Accept the Terms and Conditions>, and click the button labeled, B<Install Now>, 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/install_now.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

The installer takes a few seconds to do its job, but should come back with a screen saying everything's all set, and allow you to start working with your fancy, new Dada Mail. 

All set! And that's how you install Dada Mail using Mojo Marketplace. 

=head2 Upgrading your Mojo Marketplace to a Self-Installed Dada Mail-Pro Dada

=head2 Decouple your Dada Mail install from Mojo Marketplace

The first step you want to take B<before> upgrading your Mojo Marketplace installation of Dada Mail is to B<decouple> your Dada Mail, from Mojo Marketplace. This is done within the Mojo Marketplace. 

Once again, enter into Mojo Marketplace, and click on B<Scripts and Platforms>. Click on the button labeld, B<View My Installs>. 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/view_my_installs.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

The screen should refresh and show all your current Mojo Marketplace installations, including your Dada Mail. 

Under Dada Mail, click on the link labeled, B<Uninstall> (as scary as that sounds, this somewhat mislabled link will not uninstall your Dada Mail, when clicked!) 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/click_uninstall_link.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

A modal window will appear, giving you a few, again - slightly confusing options.

B<One> of these options is to, B<remove Dada Mail, from your list of installation applications>. This is what we want to do:

Click the button labeled, B<Remove From List> (Option #2), and then confirm this removal.  

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/click_remove_from_list_button.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

This option will leave your installation of Dada Mail completely alone, yet stop Mojo Marketplace from administrating it.  

Once that's completed, you can start administrating the intallation of your Dada Mail, yourself. 

=head2 Self-Install Dada Mail/Pro Dada

You'll want to now find the installation directory used by Simple Script/Mojo Marketplace. In our example, we installed Dada Mail via the Mojo Marketplace at this URL: 

L<http://dadademo.com/mojomarketplace> 

B<mojomarketplace> is our installation directory. If we peak inside this directory, using an FTP program (Transmit, in this case), or using the File Manager, provided with cPanel, we'll see that within this diretory is another directory named, B<dada> - and THAT's Dada Mail, installed on your account. 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/find_dada_directory.jpg" width="719" height="607" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

From here, all we need to do is follow the regular, B<Upgrade Dada Mail> directions, 

L<https://dadamailproject.com/d/upgrade_dada_mail.pod.html>

Here's the basic steps: I<(See the full docs if you have more questions)>

B<Rename the, "dada" Directory:> I'm going to rename this directory, B<dada-6_4_1> to reflect what version of Dada Mail was installed by Mojo Marketplace, 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/rename_dada_directory.jpg" width="719" height="607" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html


B<Upload the Dada Mail distro, as well as the, B<uncompress_dada.cgi> helper script,>

in this example, we're upgrading to B<v6.5.0> of Pro Dada, so the distro is named, B<pro_dada-6_5_0.tar.gz>. It's possible there's already a copy of the B<uncompress_dada.cgi> script in this directory, you'll still need to put up a specific copy, for this exact version of Pro Dada. Pro Dada copies of the distro and this helper script can be found at the Pro Dada subscribers-only part of the Dada Mail support site: 

L<https://dadamailproject.com/pro_dada>

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/put_pro_dada_distro.jpg" width="719" height="607" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

B<Change the permission of the, uncompress_dada.cgi script to, "755">: this allows this script to be executed, and the script itself handles a whole bunch of things for us, so we don't have to. 

B<Visit the, "uncompress_dada.cgi" script in your web browser>

Since our original install was at: 

L<http://dadademo.com/mojomarketplace> 

The address of the fresh copy of the B<uncompress_dada.cgi> would be at: 

L<http://dadademo.com/mojomarketplace/uncompress_dada.cgi>

Simply visit this URL in your web browser to have this script unroll this distro, and set things up. Click on the large link on the bottom to start up the included Dada Mail Installer! 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/click_install_and_configure_dada_mail.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html


Once in the installer, you will want to choose, B<Upgrade>, and hopefully, the path to your current B<.dada_files> directory will be filled out. Click on the button labeled, B<Continue> to configure your new copy of Dada Mail/Pro Dada, 

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/click_continue.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html


What's fantastic about moving from a Mojo Marketplace installation of Dada Mail and your own self-installed copy of Dada Mail/Pro Dada, is that there's nothing you will now need to reconfigure - all the values presented to you are just fine! If you're happy with how everything looks, simple click on the button labeled, B<Configure Dada Mail/Pro Dada!> at the bottom of the screen.

=begin html

<p style="text-align:center">
<img src="https://dadamailproject.com/images/v6_5_0-mojo_marketplace_upgrade/click_configure_pro_dada.jpg" width="800" height="589" style="border:1px solid black" /><br /> 
<em></em> 
</p>

=end html

Pro Dada has many advanced configuration options above this button that Dada Mail does not have, and which you may want to play around with. A complete walk-through of the many additional, advanced options is covered here: 

L<https://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html>

Click on the button labeled, B<Move the, 'dada/installer' Directory, Disable the, 'install.cgi' script>, and then the button labeled, B<Start working Dada Mail/Pro Dada!>.

Once the screen is refreshed, you've successfully self-installed your own copy of Dada Mail/Pro Dada, starting with a Mojo Marketplace installation of Pro Dada. Good work! 

=cut