=pod

=head1 Upgrading Dada Mail

=head1 Introduction

These docs will guide you through an installation of Dada Mail, originally installed and configured with the included Dada Mail Installer. 

=begin html

<div class="see_also">
<p> For information on how to upgrade Dada Mail from an install that wasn't done using the inclused Dada Mail Installer, see, <a href="./FAQ-install_upgrade.pod.html#upgrading_dada_mail_from_different_installation_types">Upgrading Dada Mail From Different Installation Types</a></p>
</div> 

=end html

=head1 Step #1 Rename the, "dada" Directory

Dada Mail, "The Program" is the collection of files and directories that are in the directory called, C<dada>. 

The, C<dada> directory has a structure like this: 

 cgi-bin (directory)
    - dada (directory, _lower_ case)
        - mail.cgi 
        - DADA (directory, UPPER case)
            - App (directory)
            - Config.pm
            - etc, etc, etc

This is Dada Mail, B<The Program>

Simply rename this directory on your hosting account from: 

 dada

to something like:

 dada-old_ver

Moving the directory: 

=over 

=item * Keeps a backup that is known to work 

=item * Makes sure we don't overwrite the old version of the program with the new version

=item * Makes sure we don't mix up the old version of Dada Mail with the new version of Dada Mail 

=back

=head2 Step #2 Install the new Dada Mail

Upgrading will now be similar to installing Dada Mail (L<http://dadamailproject.com/d/install_dada_mail.pod.html>) 

Except, that on the first screen, instead of choosing, "Install" - 

=head2 Choose, "Upgrade"

The first screen of the installer will ask you if you'd like to B<Install>, or B<Upgrade> Dada Mail. Choose, B<Upgrade>. 

A new form field will appear labeled, B<Current .dada_files Location>. 

If it can automatically be found, the textbox will already be filled with
the absolute path to the parent directory of where the C<.dada_files> directory lives. If this path looks correct, click, B<Continue...>. 

If this isn't the correct location, or no location was pre-filled in, fill in the correct location manually. The installer shouldn't 
allow you to continue, unless this directory is successfully found. 

=head2 Upgrade Options

Two new options are presented to you in the installer, if you are B<upgrading>. 

=head3 Create a new .dada_config file

Select this option if you are B<upgrading between major versions> of Dada Mail. For example, version B<5>.0.0 to version B<6>.0.0 or, 
from version 6.B<0>.0 to version 6.B<2>.0. 

=head4 Why Create a new .dada_config file? 

Changes are periodically made to Dada Mail's default configuration and it's a good idea to have the installer create a new C<.dada_config> file to 
take advantage of any new enhancements and also to keep your C<.dada_config> file current and compatible with your new copy of 
Dada Mail. If you are unsure, use the option to create a new .dada_config file>

The Installer will read your old C<.dada_config> file and pre-fill in the configuration that can be set on this screen. Give it a quick look-over and make sure the information looks correct and make any changes that you would like. This is a good oppourtunity to add/remove installed plugins, or do more advanced configurations, like set up Amazon SES sending. 

If you have manually editing the C<.dada_config> file, note that the installer does not support moving over any manual edits when you upgrade. You will need to manually copy over these configurations after the upgrade is completed. The Installer will make a backup of your previous C<.dada_config> file, to make this easy to do. 

=head3  Use the current .dada_config file

Select this option if you are upgrading between minor versions of Dada Mail. For example, version 5.0.B<0> to 5.0.B<1>. 

The rest of the installer form will be hidden, as no extra configuration is needed. 


=head2 Changelog 

It's a B<I<very very>> good idea to look at the changelog and note B<any> incompatibilities between versions. It's possible that incompatibilities could break your installation, when you upgrade. 

Changelog: L<http://dadamailproject.com/d/changes_6_x.pod.html>
