=pod

=head1 Upgrading Dada Mail

Here's the skinny on upgrading Dada Mail - 

There's:

=over

=item * Dada Mail, "The Program"

This is the group of files that's most likely located in your cgi-bin, it has a directory structure like this: 

 cgi-bin (directory)
    - dada (directory, _lower_ case)
        - mail.cgi 
        - DADA (directory, UPPER case)
            - App (directory)
            - Config.pm
            - etc, etc, etc

This is the actual program of Dada Mail. When upgrading, you basically replace these files, with the new version of Dada Mail, and configure it the same - if you understand that, that's all there is to upgrading. If you're a little shaky, read on for more information.  

=item * The Dada Mail List Files

This is the group of files that represent your various lists. Hopefully, they are B<not> located in the cgi-bin, nor are they anywhere in (somewhere) the actual program files of Dada Mail.

Usually, they are in the directory you specified in the Config.pm's variable, B<$FILES>. 

In an upgrade, these files do not go anywhere - they stay put. Since everything that makes a list a list is included in these files (the list settings, the list archives, the list subscribers, etc), upgrading Dada Mail won't erase your lists settings, archives, subscriptions, etc.

=back

=head2 Step #0  Read the change logs, NOTES, etc. 

Things change between versions. Before even beginning to upgrade, make sure that you understand the changes in the program and how they may affect your current installation. 

The changelog is located here: 

http://dadamailproject.com/support/documentation/changes_4_x.pod.html

If you are upgrading from Dada Mail 3.x to Dada Mail 4.x  also see: 

=head3 Dada Mail 3.x to Dada Mail 34x Guide

L<http://dadamailproject.com/support/documentation/dada3_to_dada4.pod.html>

=head2 Step #1 Back Up EVERYTHING

Before you begin anything, back up B<both> The Program Itself and The List Files) locations. You never know. You can backup the files by making a copy of them on your server, downloading the files onto your desktop computer, etc. Doesn't matter, but always have a reliable backup. 

=head2 Step #2 Move the Program Files out of the way. 

Remember, Dada Mail, "The Program" - this is the, "dada" directory (and it's contents) that's usually located in your cgi-bin. To do an upgrade, we need this out of the way. 

This is what I do:

I<After> I make a backup (see Step 1), I simply rename this directory on the server from: 

 dada

to something like:

 dada-backup

Pretty simple and straightforward, no? If I want to get really fancy, I rename it the version of Dada Mail it was, ala: 

 dada-3_0_5

This move is more important than you might think - it keeps a backup that is known to work handy, it also makes sure that we're not overwriting the old files, with new files. It works like insurance: the new version doesn't work for some reason?  Rename the new copy something like, "dada-new_but_busted" and move the old version back to just, "dada". 

=head2 Step #3 Install the new Dada Mail

From then on, you can just follow the instructions for an installation of Dada Mail: 

http://dadamailproject.com/installation/

Download Dada Mail, upload the new, "dada" directory, tweak the Config.pm file, chmod 755 the mail.cgi script, etc. Takes but a few minutes (mostly waiting for the file upload to complete) and you are done,  you have an upgraded version of Dada Mail and you are pretty happy. 

One thing that you want to make sure of, is when you are configuring the new copy of Dada Mail, that you set the Config.pm variables similar to what the old copy of Dada Mail had. I say, "similar", since some of these variables do change between versions - but this is what the, "NOTES" and changelog are for. 

=head2 Upgrading a, "Basic" Installation

If you set up Dada Mail using the, "Basic" installation instructions, we recommend switching to the Contemporary installation setup. Here's how: 

http://dadamailproject.com/support/documentation/FAQ-basic_2_advanced_installation.pod.html
